/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {80, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {41, 6, 1};

static const casadi_real casadi_zeros[80] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* step:(i0[6],i1[2])->(o0[6]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, *w04=w+9, w05, w06, w07, w08, *w09=w+15, *w10=w+21;
  casadi_real *w11=w+27;
  const casadi_real *cr, *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w00);
  /* #1: @1 = 0.0133333 */
  w01 = 1.3333333333333334e-02;
  /* #2: @2 = @0[2] */
  for (rr=(&w02), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #3: @3 = @0[3] */
  for (rr=(&w03), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 2, w04);
  /* #5: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #6: @6 = @0[4] */
  for (rr=(&w06), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #7: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #8: @5 = (@5*@6) */
  w05 *= w06;
  /* #9: @5 = (-@5) */
  w05 = (- w05 );
  /* #10: @6 = @4[0] */
  for (rr=(&w06), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #11: @7 = @0[4] */
  for (rr=(&w07), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #12: @7 = cos(@7) */
  w07 = cos( w07 );
  /* #13: @6 = (@6*@7) */
  w06 *= w07;
  /* #14: @7 = 9.81 */
  w07 = 9.8100000000000005e+00;
  /* #15: @6 = (@6-@7) */
  w06 -= w07;
  /* #16: @7 = @0[5] */
  for (rr=(&w07), cs=w00+5; cs!=w00+6; cs+=1) *rr++ = *cs;
  /* #17: @8 = @4[1] */
  for (rr=(&w08), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #18: @9 = vertcat(@2, @3, @5, @6, @7, @8) */
  rr=w09;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  /* #19: @2 = 0.04 */
  w02 = 4.0000000000000001e-02;
  /* #20: @10 = (@2*@9) */
  for (i=0, rr=w10, cs=w09; i<6; ++i) (*rr++)  = (w02*(*cs++));
  /* #21: @10 = (@0+@10) */
  for (i=0, rr=w10, cr=w00, cs=w10; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #22: @2 = @10[2] */
  for (rr=(&w02), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #23: @3 = @10[3] */
  for (rr=(&w03), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #24: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #25: @6 = @10[4] */
  for (rr=(&w06), cs=w10+4; cs!=w10+5; cs+=1) *rr++ = *cs;
  /* #26: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #27: @5 = (@5*@6) */
  w05 *= w06;
  /* #28: @5 = (-@5) */
  w05 = (- w05 );
  /* #29: @6 = @4[0] */
  for (rr=(&w06), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #30: @7 = @10[4] */
  for (rr=(&w07), cs=w10+4; cs!=w10+5; cs+=1) *rr++ = *cs;
  /* #31: @7 = cos(@7) */
  w07 = cos( w07 );
  /* #32: @6 = (@6*@7) */
  w06 *= w07;
  /* #33: @7 = 9.81 */
  w07 = 9.8100000000000005e+00;
  /* #34: @6 = (@6-@7) */
  w06 -= w07;
  /* #35: @7 = @10[5] */
  for (rr=(&w07), cs=w10+5; cs!=w10+6; cs+=1) *rr++ = *cs;
  /* #36: @8 = @4[1] */
  for (rr=(&w08), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #37: @10 = vertcat(@2, @3, @5, @6, @7, @8) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  /* #38: @11 = (2.*@10) */
  for (i=0, rr=w11, cs=w10; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #39: @9 = (@9+@11) */
  for (i=0, rr=w09, cs=w11; i<6; ++i) (*rr++) += (*cs++);
  /* #40: @2 = 0.04 */
  w02 = 4.0000000000000001e-02;
  /* #41: @10 = (@2*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w02*(*cs++));
  /* #42: @10 = (@0+@10) */
  for (i=0, rr=w10, cr=w00, cs=w10; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #43: @2 = @10[2] */
  for (rr=(&w02), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #44: @3 = @10[3] */
  for (rr=(&w03), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #45: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #46: @6 = @10[4] */
  for (rr=(&w06), cs=w10+4; cs!=w10+5; cs+=1) *rr++ = *cs;
  /* #47: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #48: @5 = (@5*@6) */
  w05 *= w06;
  /* #49: @5 = (-@5) */
  w05 = (- w05 );
  /* #50: @6 = @4[0] */
  for (rr=(&w06), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #51: @7 = @10[4] */
  for (rr=(&w07), cs=w10+4; cs!=w10+5; cs+=1) *rr++ = *cs;
  /* #52: @7 = cos(@7) */
  w07 = cos( w07 );
  /* #53: @6 = (@6*@7) */
  w06 *= w07;
  /* #54: @7 = 9.81 */
  w07 = 9.8100000000000005e+00;
  /* #55: @6 = (@6-@7) */
  w06 -= w07;
  /* #56: @7 = @10[5] */
  for (rr=(&w07), cs=w10+5; cs!=w10+6; cs+=1) *rr++ = *cs;
  /* #57: @8 = @4[1] */
  for (rr=(&w08), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #58: @10 = vertcat(@2, @3, @5, @6, @7, @8) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  /* #59: @11 = (2.*@10) */
  for (i=0, rr=w11, cs=w10; i<6; ++i) *rr++ = (2.* *cs++ );
  /* #60: @9 = (@9+@11) */
  for (i=0, rr=w09, cs=w11; i<6; ++i) (*rr++) += (*cs++);
  /* #61: @2 = 0.08 */
  w02 = 8.0000000000000002e-02;
  /* #62: @10 = (@2*@10) */
  for (i=0, rr=w10, cs=w10; i<6; ++i) (*rr++)  = (w02*(*cs++));
  /* #63: @10 = (@0+@10) */
  for (i=0, rr=w10, cr=w00, cs=w10; i<6; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #64: @2 = @10[2] */
  for (rr=(&w02), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #65: @3 = @10[3] */
  for (rr=(&w03), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #66: @5 = @4[0] */
  for (rr=(&w05), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #67: @6 = @10[4] */
  for (rr=(&w06), cs=w10+4; cs!=w10+5; cs+=1) *rr++ = *cs;
  /* #68: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #69: @5 = (@5*@6) */
  w05 *= w06;
  /* #70: @5 = (-@5) */
  w05 = (- w05 );
  /* #71: @6 = @4[0] */
  for (rr=(&w06), cs=w04+0; cs!=w04+1; cs+=1) *rr++ = *cs;
  /* #72: @7 = @10[4] */
  for (rr=(&w07), cs=w10+4; cs!=w10+5; cs+=1) *rr++ = *cs;
  /* #73: @7 = cos(@7) */
  w07 = cos( w07 );
  /* #74: @6 = (@6*@7) */
  w06 *= w07;
  /* #75: @7 = 9.81 */
  w07 = 9.8100000000000005e+00;
  /* #76: @6 = (@6-@7) */
  w06 -= w07;
  /* #77: @7 = @10[5] */
  for (rr=(&w07), cs=w10+5; cs!=w10+6; cs+=1) *rr++ = *cs;
  /* #78: @8 = @4[1] */
  for (rr=(&w08), cs=w04+1; cs!=w04+2; cs+=1) *rr++ = *cs;
  /* #79: @10 = vertcat(@2, @3, @5, @6, @7, @8) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  /* #80: @9 = (@9+@10) */
  for (i=0, rr=w09, cs=w10; i<6; ++i) (*rr++) += (*cs++);
  /* #81: @9 = (@1*@9) */
  for (i=0, rr=w09, cs=w09; i<6; ++i) (*rr++)  = (w01*(*cs++));
  /* #82: @0 = (@0+@9) */
  for (i=0, rr=w00, cs=w09; i<6; ++i) (*rr++) += (*cs++);
  /* #83: output[0][0] = @0 */
  casadi_copy(w00, 6, res[0]);
  return 0;
}

/* step_acc10:(i0[6],i1[2x10])->(o0[6x10]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w0=w+33, *w1=w+39, *w2=w+41;
  const casadi_real **arg1=arg+2;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 2, w1);
  /* #2: @2 = step(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=w2;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #3: output[0][0] = @2 */
  casadi_copy(w2, 6, res[0]);
  /* #4: @1 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+2 : 0, 2, w1);
  /* #5: @0 = step(@2, @1) */
  arg1[0]=w2;
  arg1[1]=w1;
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 6, res[0]+6);
  /* #7: @1 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+4 : 0, 2, w1);
  /* #8: @2 = step(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=w2;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: output[0][2] = @2 */
  if (res[0]) casadi_copy(w2, 6, res[0]+12);
  /* #10: @1 = input[1][3] */
  casadi_copy(arg[1] ? arg[1]+6 : 0, 2, w1);
  /* #11: @0 = step(@2, @1) */
  arg1[0]=w2;
  arg1[1]=w1;
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 6, res[0]+18);
  /* #13: @1 = input[1][4] */
  casadi_copy(arg[1] ? arg[1]+8 : 0, 2, w1);
  /* #14: @2 = step(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=w2;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #15: output[0][4] = @2 */
  if (res[0]) casadi_copy(w2, 6, res[0]+24);
  /* #16: @1 = input[1][5] */
  casadi_copy(arg[1] ? arg[1]+10 : 0, 2, w1);
  /* #17: @0 = step(@2, @1) */
  arg1[0]=w2;
  arg1[1]=w1;
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #18: output[0][5] = @0 */
  if (res[0]) casadi_copy(w0, 6, res[0]+30);
  /* #19: @1 = input[1][6] */
  casadi_copy(arg[1] ? arg[1]+12 : 0, 2, w1);
  /* #20: @2 = step(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=w2;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #21: output[0][6] = @2 */
  if (res[0]) casadi_copy(w2, 6, res[0]+36);
  /* #22: @1 = input[1][7] */
  casadi_copy(arg[1] ? arg[1]+14 : 0, 2, w1);
  /* #23: @0 = step(@2, @1) */
  arg1[0]=w2;
  arg1[1]=w1;
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #24: output[0][7] = @0 */
  if (res[0]) casadi_copy(w0, 6, res[0]+42);
  /* #25: @1 = input[1][8] */
  casadi_copy(arg[1] ? arg[1]+16 : 0, 2, w1);
  /* #26: @2 = step(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=w2;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #27: output[0][8] = @2 */
  if (res[0]) casadi_copy(w2, 6, res[0]+48);
  /* #28: @1 = input[1][9] */
  casadi_copy(arg[1] ? arg[1]+18 : 0, 2, w1);
  /* #29: @0 = step(@2, @1) */
  arg1[0]=w2;
  arg1[1]=w1;
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #30: output[0][9] = @0 */
  if (res[0]) casadi_copy(w0, 6, res[0]+54);
  return 0;
}

/* roll:(i0[6],i1[2x40])->(o0[6x40]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w0=w+47, *w2=w+73;
  const casadi_real **arg1=arg+2, *wr1;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w0);
  /* #1: @1 = input[1][0] */
  wr1 = arg[1] ? arg[1] : casadi_zeros;
  /* #2: @2 = step_acc10(@0, @1) */
  arg1[0]=w0;
  arg1[1]=wr1;
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #3: output[0][0] = @2 */
  casadi_copy(w2, 60, res[0]);
  /* #4: {NULL, @0} = horzsplit(@2) */
  casadi_copy(w2+54, 6, w0);
  /* #5: @1 = input[1][1] */
  wr1 = arg[1] ? arg[1]+20 : casadi_zeros;
  /* #6: @2 = step_acc10(@0, @1) */
  arg1[0]=w0;
  arg1[1]=wr1;
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #7: output[0][1] = @2 */
  if (res[0]) casadi_copy(w2, 60, res[0]+60);
  /* #8: {NULL, @0} = horzsplit(@2) */
  casadi_copy(w2+54, 6, w0);
  /* #9: @1 = input[1][2] */
  wr1 = arg[1] ? arg[1]+40 : casadi_zeros;
  /* #10: @2 = step_acc10(@0, @1) */
  arg1[0]=w0;
  arg1[1]=wr1;
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #11: output[0][2] = @2 */
  if (res[0]) casadi_copy(w2, 60, res[0]+120);
  /* #12: {NULL, @0} = horzsplit(@2) */
  casadi_copy(w2+54, 6, w0);
  /* #13: @1 = input[1][3] */
  wr1 = arg[1] ? arg[1]+60 : casadi_zeros;
  /* #14: @2 = step_acc10(@0, @1) */
  arg1[0]=w0;
  arg1[1]=wr1;
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #15: output[0][3] = @2 */
  if (res[0]) casadi_copy(w2, 60, res[0]+180);
  return 0;
}

/* F_roll:(i0[80],i1[6])->(o0[41x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+1, *rr, *w0=w+133, *w2=w+219, *w3=w+459, *w4=w+705;
  const casadi_real **arg1=arg+2, *cs, *wr1;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 6, w0);
  /* #1: @1 = input[0][0] */
  wr1 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @1 = reshape(@1) */
  /* #3: @2 = roll(@0, @1) */
  arg1[0]=w0;
  arg1[1]=wr1;
  res1[0]=w2;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @3 = horzcat(@0, @2) */
  rr=w3;
  for (i=0, cs=w0; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<240; ++i) *rr++ = *cs++;
  /* #5: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<41; ++i) for (j=0; j<6; ++j) rr[i+j*41] = *cs++;
  /* #6: output[0][0] = @4 */
  casadi_copy(w4, 246, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int F_roll(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_roll_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_roll_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_roll_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_roll_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_roll_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_roll_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_roll_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_roll_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_roll_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_roll_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_roll_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_roll_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_roll_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_roll_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_roll_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 951;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_roll_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 951*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
