/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fam_672c18526ebfca3b_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[17] = 
  {4, 10, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 4, 0, 1, 2,
  3};
static const casadi_int casadi_s1[3] = {60, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {1, 60, 1};
static const casadi_int casadi_s4[304] = 
  {4, 61, 0, 0, 4, 8, 12, 16,
  20, 24, 28, 32, 36, 40, 44, 48,
  52, 56, 60, 64, 68, 72, 76, 80,
  84, 88, 92, 96, 100, 104, 108, 112,
  116, 120, 124, 128, 132, 136, 140, 144,
  148, 152, 156, 160, 164, 168, 172, 176,
  180, 184, 188, 192, 196, 200, 204, 208,
  212, 216, 220, 224, 228, 232, 236, 240,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3,
  0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s5[247] = 
  {61, 4, 0, 60, 120, 180, 240, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12, 13, 14, 15, 16, 17,
  18, 19, 20, 21, 22, 23, 24, 25,
  26, 27, 28, 29, 30, 31, 32, 33,
  34, 35, 36, 37, 38, 39, 40, 41,
  42, 43, 44, 45, 46, 47, 48, 49,
  50, 51, 52, 53, 54, 55, 56, 57,
  58, 59, 60, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33, 34, 35, 36, 37,
  38, 39, 40, 41, 42, 43, 44, 45,
  46, 47, 48, 49, 50, 51, 52, 53,
  54, 55, 56, 57, 58, 59, 60, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12, 13, 14, 15, 16, 17,
  18, 19, 20, 21, 22, 23, 24, 25,
  26, 27, 28, 29, 30, 31, 32, 33,
  34, 35, 36, 37, 38, 39, 40, 41,
  42, 43, 44, 45, 46, 47, 48, 49,
  50, 51, 52, 53, 54, 55, 56, 57,
  58, 59, 60, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33, 34, 35, 36, 37,
  38, 39, 40, 41, 42, 43, 44, 45,
  46, 47, 48, 49, 50, 51, 52, 53,
  54, 55, 56, 57, 58, 59, 60};
static const casadi_int casadi_s6[3] = {61, 4, 1};

static const casadi_real casadi_zeros[240] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* step:(i0[4],i1,i2)->(o0[4]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, *w09=w+12, *w10=w+16;
  casadi_real *w11=w+20;
  const casadi_real *cr, *cs;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 4, w00);
  /* #1: @1 = 0.00166667 */
  w01 = 1.6666666666666668e-03;
  /* #2: @2 = @0[2] */
  for (rr=(&w02), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #3: @3 = @0[3] */
  for (rr=(&w03), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #4: @4 = -56.8489 */
  w04 = -5.6848921350274701e+01;
  /* #5: @5 = @0[0] */
  for (rr=(&w05), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #6: @4 = (@4*@5) */
  w04 *= w05;
  /* #7: @5 = 0.120637 */
  w05 = 1.2063715789784805e-01;
  /* #8: @5 = (@5*@2) */
  w05 *= w02;
  /* #9: @4 = (@4-@5) */
  w04 -= w05;
  /* #10: @5 = 3.14159 */
  w05 = 3.1415926535897931e+00;
  /* #11: @6 = input[2][0] */
  w06 = arg[2] ? arg[2][0] : 0;
  /* #12: @5 = (@5*@6) */
  w05 *= w06;
  /* #13: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #14: @7 = input[1][0] */
  w07 = arg[1] ? arg[1][0] : 0;
  /* #15: @5 = (@5*@7) */
  w05 *= w07;
  /* #16: @4 = (@4+@5) */
  w04 += w05;
  /* #17: @5 = -909.583 */
  w05 = -9.0958274160439521e+02;
  /* #18: @8 = @0[1] */
  for (rr=(&w08), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #19: @5 = (@5*@8) */
  w05 *= w08;
  /* #20: @8 = 0.482549 */
  w08 = 4.8254863159139222e-01;
  /* #21: @8 = (@8*@3) */
  w08 *= w03;
  /* #22: @5 = (@5-@8) */
  w05 -= w08;
  /* #23: @8 = 6.28319 */
  w08 = 6.2831853071795862e+00;
  /* #24: @8 = (@8*@6) */
  w08 *= w06;
  /* #25: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #26: @8 = (@8*@7) */
  w08 *= w07;
  /* #27: @5 = (@5+@8) */
  w05 += w08;
  /* #28: @9 = vertcat(@2, @3, @4, @5) */
  rr=w09;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  /* #29: @2 = 0.005 */
  w02 = 5.0000000000000001e-03;
  /* #30: @10 = (@2*@9) */
  for (i=0, rr=w10, cs=w09; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #31: @10 = (@0+@10) */
  for (i=0, rr=w10, cr=w00, cs=w10; i<4; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #32: @2 = @10[2] */
  for (rr=(&w02), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #33: @3 = @10[3] */
  for (rr=(&w03), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #34: @4 = -56.8489 */
  w04 = -5.6848921350274701e+01;
  /* #35: @5 = @10[0] */
  for (rr=(&w05), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #36: @4 = (@4*@5) */
  w04 *= w05;
  /* #37: @5 = 0.120637 */
  w05 = 1.2063715789784805e-01;
  /* #38: @5 = (@5*@2) */
  w05 *= w02;
  /* #39: @4 = (@4-@5) */
  w04 -= w05;
  /* #40: @5 = 3.14159 */
  w05 = 3.1415926535897931e+00;
  /* #41: @5 = (@5*@6) */
  w05 *= w06;
  /* #42: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #43: @5 = (@5*@7) */
  w05 *= w07;
  /* #44: @4 = (@4+@5) */
  w04 += w05;
  /* #45: @5 = -909.583 */
  w05 = -9.0958274160439521e+02;
  /* #46: @8 = @10[1] */
  for (rr=(&w08), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #47: @5 = (@5*@8) */
  w05 *= w08;
  /* #48: @8 = 0.482549 */
  w08 = 4.8254863159139222e-01;
  /* #49: @8 = (@8*@3) */
  w08 *= w03;
  /* #50: @5 = (@5-@8) */
  w05 -= w08;
  /* #51: @8 = 6.28319 */
  w08 = 6.2831853071795862e+00;
  /* #52: @8 = (@8*@6) */
  w08 *= w06;
  /* #53: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #54: @8 = (@8*@7) */
  w08 *= w07;
  /* #55: @5 = (@5+@8) */
  w05 += w08;
  /* #56: @10 = vertcat(@2, @3, @4, @5) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  /* #57: @11 = (2.*@10) */
  for (i=0, rr=w11, cs=w10; i<4; ++i) *rr++ = (2.* *cs++ );
  /* #58: @9 = (@9+@11) */
  for (i=0, rr=w09, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #59: @2 = 0.005 */
  w02 = 5.0000000000000001e-03;
  /* #60: @10 = (@2*@10) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #61: @10 = (@0+@10) */
  for (i=0, rr=w10, cr=w00, cs=w10; i<4; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #62: @2 = @10[2] */
  for (rr=(&w02), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #63: @3 = @10[3] */
  for (rr=(&w03), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #64: @4 = -56.8489 */
  w04 = -5.6848921350274701e+01;
  /* #65: @5 = @10[0] */
  for (rr=(&w05), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #66: @4 = (@4*@5) */
  w04 *= w05;
  /* #67: @5 = 0.120637 */
  w05 = 1.2063715789784805e-01;
  /* #68: @5 = (@5*@2) */
  w05 *= w02;
  /* #69: @4 = (@4-@5) */
  w04 -= w05;
  /* #70: @5 = 3.14159 */
  w05 = 3.1415926535897931e+00;
  /* #71: @5 = (@5*@6) */
  w05 *= w06;
  /* #72: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #73: @5 = (@5*@7) */
  w05 *= w07;
  /* #74: @4 = (@4+@5) */
  w04 += w05;
  /* #75: @5 = -909.583 */
  w05 = -9.0958274160439521e+02;
  /* #76: @8 = @10[1] */
  for (rr=(&w08), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #77: @5 = (@5*@8) */
  w05 *= w08;
  /* #78: @8 = 0.482549 */
  w08 = 4.8254863159139222e-01;
  /* #79: @8 = (@8*@3) */
  w08 *= w03;
  /* #80: @5 = (@5-@8) */
  w05 -= w08;
  /* #81: @8 = 6.28319 */
  w08 = 6.2831853071795862e+00;
  /* #82: @8 = (@8*@6) */
  w08 *= w06;
  /* #83: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #84: @8 = (@8*@7) */
  w08 *= w07;
  /* #85: @5 = (@5+@8) */
  w05 += w08;
  /* #86: @10 = vertcat(@2, @3, @4, @5) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  /* #87: @11 = (2.*@10) */
  for (i=0, rr=w11, cs=w10; i<4; ++i) *rr++ = (2.* *cs++ );
  /* #88: @9 = (@9+@11) */
  for (i=0, rr=w09, cs=w11; i<4; ++i) (*rr++) += (*cs++);
  /* #89: @2 = 0.01 */
  w02 = 1.0000000000000000e-02;
  /* #90: @10 = (@2*@10) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #91: @10 = (@0+@10) */
  for (i=0, rr=w10, cr=w00, cs=w10; i<4; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #92: @2 = @10[2] */
  for (rr=(&w02), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #93: @3 = @10[3] */
  for (rr=(&w03), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #94: @4 = -56.8489 */
  w04 = -5.6848921350274701e+01;
  /* #95: @5 = @10[0] */
  for (rr=(&w05), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #96: @4 = (@4*@5) */
  w04 *= w05;
  /* #97: @5 = 0.120637 */
  w05 = 1.2063715789784805e-01;
  /* #98: @5 = (@5*@2) */
  w05 *= w02;
  /* #99: @4 = (@4-@5) */
  w04 -= w05;
  /* #100: @5 = 3.14159 */
  w05 = 3.1415926535897931e+00;
  /* #101: @5 = (@5*@6) */
  w05 *= w06;
  /* #102: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #103: @5 = (@5*@7) */
  w05 *= w07;
  /* #104: @4 = (@4+@5) */
  w04 += w05;
  /* #105: @5 = -909.583 */
  w05 = -9.0958274160439521e+02;
  /* #106: @8 = @10[1] */
  for (rr=(&w08), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #107: @5 = (@5*@8) */
  w05 *= w08;
  /* #108: @8 = 0.482549 */
  w08 = 4.8254863159139222e-01;
  /* #109: @8 = (@8*@3) */
  w08 *= w03;
  /* #110: @5 = (@5-@8) */
  w05 -= w08;
  /* #111: @8 = 6.28319 */
  w08 = 6.2831853071795862e+00;
  /* #112: @8 = (@8*@6) */
  w08 *= w06;
  /* #113: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #114: @8 = (@8*@7) */
  w08 *= w07;
  /* #115: @5 = (@5+@8) */
  w05 += w08;
  /* #116: @10 = vertcat(@2, @3, @4, @5) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  /* #117: @9 = (@9+@10) */
  for (i=0, rr=w09, cs=w10; i<4; ++i) (*rr++) += (*cs++);
  /* #118: @9 = (@1*@9) */
  for (i=0, rr=w09, cs=w09; i<4; ++i) (*rr++)  = (w01*(*cs++));
  /* #119: @0 = (@0+@9) */
  for (i=0, rr=w00, cs=w09; i<4; ++i) (*rr++) += (*cs++);
  /* #120: output[0][0] = @0 */
  casadi_copy(w00, 4, res[0]);
  return 0;
}

/* step_acc10:(i0[4],i1[1x10],i2[1x10])->(o0[4x10]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w0=w+24, w1, w2, *w3=w+30;
  const casadi_real **arg1=arg+3;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 4, w0);
  /* #1: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #2: @2 = input[2][0] */
  w2 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = step(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w3;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][0] = @3 */
  casadi_copy(w3, 4, res[0]);
  /* #5: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #6: @2 = input[2][1] */
  w2 = arg[2] ? arg[2][1] : 0;
  /* #7: @0 = step(@3, @1, @2) */
  arg1[0]=w3;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 4, res[0]+4);
  /* #9: @1 = input[1][2] */
  w1 = arg[1] ? arg[1][2] : 0;
  /* #10: @2 = input[2][2] */
  w2 = arg[2] ? arg[2][2] : 0;
  /* #11: @3 = step(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w3;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: output[0][2] = @3 */
  if (res[0]) casadi_copy(w3, 4, res[0]+8);
  /* #13: @1 = input[1][3] */
  w1 = arg[1] ? arg[1][3] : 0;
  /* #14: @2 = input[2][3] */
  w2 = arg[2] ? arg[2][3] : 0;
  /* #15: @0 = step(@3, @1, @2) */
  arg1[0]=w3;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #16: output[0][3] = @0 */
  if (res[0]) casadi_copy(w0, 4, res[0]+12);
  /* #17: @1 = input[1][4] */
  w1 = arg[1] ? arg[1][4] : 0;
  /* #18: @2 = input[2][4] */
  w2 = arg[2] ? arg[2][4] : 0;
  /* #19: @3 = step(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w3;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][4] = @3 */
  if (res[0]) casadi_copy(w3, 4, res[0]+16);
  /* #21: @1 = input[1][5] */
  w1 = arg[1] ? arg[1][5] : 0;
  /* #22: @2 = input[2][5] */
  w2 = arg[2] ? arg[2][5] : 0;
  /* #23: @0 = step(@3, @1, @2) */
  arg1[0]=w3;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #24: output[0][5] = @0 */
  if (res[0]) casadi_copy(w0, 4, res[0]+20);
  /* #25: @1 = input[1][6] */
  w1 = arg[1] ? arg[1][6] : 0;
  /* #26: @2 = input[2][6] */
  w2 = arg[2] ? arg[2][6] : 0;
  /* #27: @3 = step(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w3;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #28: output[0][6] = @3 */
  if (res[0]) casadi_copy(w3, 4, res[0]+24);
  /* #29: @1 = input[1][7] */
  w1 = arg[1] ? arg[1][7] : 0;
  /* #30: @2 = input[2][7] */
  w2 = arg[2] ? arg[2][7] : 0;
  /* #31: @0 = step(@3, @1, @2) */
  arg1[0]=w3;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #32: output[0][7] = @0 */
  if (res[0]) casadi_copy(w0, 4, res[0]+28);
  /* #33: @1 = input[1][8] */
  w1 = arg[1] ? arg[1][8] : 0;
  /* #34: @2 = input[2][8] */
  w2 = arg[2] ? arg[2][8] : 0;
  /* #35: @3 = step(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w3;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #36: output[0][8] = @3 */
  if (res[0]) casadi_copy(w3, 4, res[0]+32);
  /* #37: @1 = input[1][9] */
  w1 = arg[1] ? arg[1][9] : 0;
  /* #38: @2 = input[2][9] */
  w2 = arg[2] ? arg[2][9] : 0;
  /* #39: @0 = step(@3, @1, @2) */
  arg1[0]=w3;
  arg1[1]=(&w1);
  arg1[2]=(&w2);
  res1[0]=w0;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #40: output[0][9] = @0 */
  if (res[0]) casadi_copy(w0, 4, res[0]+36);
  return 0;
}

/* roll:(i0[4],i1[1x60],i2[1x60])->(o0[4x60]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w0=w+34, *w3=w+58;
  const casadi_real **arg1=arg+3, *wr1, *wr2;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 4, w0);
  /* #1: @1 = input[1][0] */
  wr1 = arg[1] ? arg[1] : casadi_zeros;
  /* #2: @2 = input[2][0] */
  wr2 = arg[2] ? arg[2] : casadi_zeros;
  /* #3: @3 = step_acc10(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=wr1;
  arg1[2]=wr2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][0] = @3 */
  casadi_copy(w3, 40, res[0]);
  /* #5: {NULL, @0} = horzsplit(@3) */
  casadi_copy(w3+36, 4, w0);
  /* #6: @1 = input[1][1] */
  wr1 = arg[1] ? arg[1]+10 : casadi_zeros;
  /* #7: @2 = input[2][1] */
  wr2 = arg[2] ? arg[2]+10 : casadi_zeros;
  /* #8: @3 = step_acc10(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=wr1;
  arg1[2]=wr2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #9: output[0][1] = @3 */
  if (res[0]) casadi_copy(w3, 40, res[0]+40);
  /* #10: {NULL, @0} = horzsplit(@3) */
  casadi_copy(w3+36, 4, w0);
  /* #11: @1 = input[1][2] */
  wr1 = arg[1] ? arg[1]+20 : casadi_zeros;
  /* #12: @2 = input[2][2] */
  wr2 = arg[2] ? arg[2]+20 : casadi_zeros;
  /* #13: @3 = step_acc10(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=wr1;
  arg1[2]=wr2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: output[0][2] = @3 */
  if (res[0]) casadi_copy(w3, 40, res[0]+80);
  /* #15: {NULL, @0} = horzsplit(@3) */
  casadi_copy(w3+36, 4, w0);
  /* #16: @1 = input[1][3] */
  wr1 = arg[1] ? arg[1]+30 : casadi_zeros;
  /* #17: @2 = input[2][3] */
  wr2 = arg[2] ? arg[2]+30 : casadi_zeros;
  /* #18: @3 = step_acc10(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=wr1;
  arg1[2]=wr2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #19: output[0][3] = @3 */
  if (res[0]) casadi_copy(w3, 40, res[0]+120);
  /* #20: {NULL, @0} = horzsplit(@3) */
  casadi_copy(w3+36, 4, w0);
  /* #21: @1 = input[1][4] */
  wr1 = arg[1] ? arg[1]+40 : casadi_zeros;
  /* #22: @2 = input[2][4] */
  wr2 = arg[2] ? arg[2]+40 : casadi_zeros;
  /* #23: @3 = step_acc10(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=wr1;
  arg1[2]=wr2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #24: output[0][4] = @3 */
  if (res[0]) casadi_copy(w3, 40, res[0]+160);
  /* #25: {NULL, @0} = horzsplit(@3) */
  casadi_copy(w3+36, 4, w0);
  /* #26: @1 = input[1][5] */
  wr1 = arg[1] ? arg[1]+50 : casadi_zeros;
  /* #27: @2 = input[2][5] */
  wr2 = arg[2] ? arg[2]+50 : casadi_zeros;
  /* #28: @3 = step_acc10(@0, @1, @2) */
  arg1[0]=w0;
  arg1[1]=wr1;
  arg1[2]=wr2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #29: output[0][5] = @3 */
  if (res[0]) casadi_copy(w3, 40, res[0]+200);
  return 0;
}

/* adj1_step:(i0[4],i1,i2,out_o0[4x1,0nz],adj_o0[4])->(adj_i0[4],adj_i1,adj_i2) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, *w01=w+4, w02, w03, *w04=w+10, w05, w06, w07, *w08=w+17, *w09=w+21, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, w29, w30;
  const casadi_real *cs;
  /* #0: @0 = input[4][0] */
  casadi_copy(arg[4], 4, w00);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w01, 4);
  /* #2: @2 = -909.583 */
  w02 = -9.0958274160439521e+02;
  /* #3: @3 = 0.00166667 */
  w03 = 1.6666666666666668e-03;
  /* #4: @4 = (@3*@0) */
  for (i=0, rr=w04, cs=w00; i<4; ++i) (*rr++)  = (w03*(*cs++));
  /* #5: {@3, @5, @6, @7} = vertsplit(@4) */
  w03 = w04[0];
  w05 = w04[1];
  w06 = w04[2];
  w07 = w04[3];
  /* #6: @2 = (@2*@7) */
  w02 *= w07;
  /* #7: (@1[1] += @2) */
  for (rr=w01+1, cs=(&w02); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #8: @2 = -56.8489 */
  w02 = -5.6848921350274701e+01;
  /* #9: @2 = (@2*@6) */
  w02 *= w06;
  /* #10: (@1[0] += @2) */
  for (rr=w01+0, cs=(&w02); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #11: @2 = 0.482549 */
  w02 = 4.8254863159139222e-01;
  /* #12: @2 = (@2*@7) */
  w02 *= w07;
  /* #13: @5 = (@5-@2) */
  w05 -= w02;
  /* #14: (@1[3] += @5) */
  for (rr=w01+3, cs=(&w05); rr!=w01+4; rr+=1) *rr += *cs++;
  /* #15: @5 = 0.120637 */
  w05 = 1.2063715789784805e-01;
  /* #16: @5 = (@5*@6) */
  w05 *= w06;
  /* #17: @3 = (@3-@5) */
  w03 -= w05;
  /* #18: (@1[2] += @3) */
  for (rr=w01+2, cs=(&w03); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #19: @0 = (@0+@1) */
  for (i=0, rr=w00, cs=w01; i<4; ++i) (*rr++) += (*cs++);
  /* #20: @8 = zeros(4x1) */
  casadi_clear(w08, 4);
  /* #21: @3 = -909.583 */
  w03 = -9.0958274160439521e+02;
  /* #22: @5 = 0.01 */
  w05 = 1.0000000000000000e-02;
  /* #23: @1 = (@5*@1) */
  for (i=0, rr=w01, cs=w01; i<4; ++i) (*rr++)  = (w05*(*cs++));
  /* #24: @9 = (2.*@4) */
  for (i=0, rr=w09, cs=w04; i<4; ++i) *rr++ = (2.* *cs++ );
  /* #25: @1 = (@1+@9) */
  for (i=0, rr=w01, cs=w09; i<4; ++i) (*rr++) += (*cs++);
  /* #26: {@5, @2, @10, @11} = vertsplit(@1) */
  w05 = w01[0];
  w02 = w01[1];
  w10 = w01[2];
  w11 = w01[3];
  /* #27: @3 = (@3*@11) */
  w03 *= w11;
  /* #28: (@8[1] += @3) */
  for (rr=w08+1, cs=(&w03); rr!=w08+2; rr+=1) *rr += *cs++;
  /* #29: @3 = -56.8489 */
  w03 = -5.6848921350274701e+01;
  /* #30: @3 = (@3*@10) */
  w03 *= w10;
  /* #31: (@8[0] += @3) */
  for (rr=w08+0, cs=(&w03); rr!=w08+1; rr+=1) *rr += *cs++;
  /* #32: @3 = 0.482549 */
  w03 = 4.8254863159139222e-01;
  /* #33: @3 = (@3*@11) */
  w03 *= w11;
  /* #34: @2 = (@2-@3) */
  w02 -= w03;
  /* #35: (@8[3] += @2) */
  for (rr=w08+3, cs=(&w02); rr!=w08+4; rr+=1) *rr += *cs++;
  /* #36: @2 = 0.120637 */
  w02 = 1.2063715789784805e-01;
  /* #37: @2 = (@2*@10) */
  w02 *= w10;
  /* #38: @5 = (@5-@2) */
  w05 -= w02;
  /* #39: (@8[2] += @5) */
  for (rr=w08+2, cs=(&w05); rr!=w08+3; rr+=1) *rr += *cs++;
  /* #40: @0 = (@0+@8) */
  for (i=0, rr=w00, cs=w08; i<4; ++i) (*rr++) += (*cs++);
  /* #41: @1 = zeros(4x1) */
  casadi_clear(w01, 4);
  /* #42: @5 = -909.583 */
  w05 = -9.0958274160439521e+02;
  /* #43: @2 = 0.005 */
  w02 = 5.0000000000000001e-03;
  /* #44: @8 = (@2*@8) */
  for (i=0, rr=w08, cs=w08; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #45: @9 = (2.*@4) */
  for (i=0, rr=w09, cs=w04; i<4; ++i) *rr++ = (2.* *cs++ );
  /* #46: @8 = (@8+@9) */
  for (i=0, rr=w08, cs=w09; i<4; ++i) (*rr++) += (*cs++);
  /* #47: {@2, @3, @12, @13} = vertsplit(@8) */
  w02 = w08[0];
  w03 = w08[1];
  w12 = w08[2];
  w13 = w08[3];
  /* #48: @5 = (@5*@13) */
  w05 *= w13;
  /* #49: (@1[1] += @5) */
  for (rr=w01+1, cs=(&w05); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #50: @5 = -56.8489 */
  w05 = -5.6848921350274701e+01;
  /* #51: @5 = (@5*@12) */
  w05 *= w12;
  /* #52: (@1[0] += @5) */
  for (rr=w01+0, cs=(&w05); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #53: @5 = 0.482549 */
  w05 = 4.8254863159139222e-01;
  /* #54: @5 = (@5*@13) */
  w05 *= w13;
  /* #55: @3 = (@3-@5) */
  w03 -= w05;
  /* #56: (@1[3] += @3) */
  for (rr=w01+3, cs=(&w03); rr!=w01+4; rr+=1) *rr += *cs++;
  /* #57: @3 = 0.120637 */
  w03 = 1.2063715789784805e-01;
  /* #58: @3 = (@3*@12) */
  w03 *= w12;
  /* #59: @2 = (@2-@3) */
  w02 -= w03;
  /* #60: (@1[2] += @2) */
  for (rr=w01+2, cs=(&w02); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #61: @0 = (@0+@1) */
  for (i=0, rr=w00, cs=w01; i<4; ++i) (*rr++) += (*cs++);
  /* #62: @2 = -909.583 */
  w02 = -9.0958274160439521e+02;
  /* #63: @3 = 0.005 */
  w03 = 5.0000000000000001e-03;
  /* #64: @1 = (@3*@1) */
  for (i=0, rr=w01, cs=w01; i<4; ++i) (*rr++)  = (w03*(*cs++));
  /* #65: @4 = (@4+@1) */
  for (i=0, rr=w04, cs=w01; i<4; ++i) (*rr++) += (*cs++);
  /* #66: {@3, @5, @14, @15} = vertsplit(@4) */
  w03 = w04[0];
  w05 = w04[1];
  w14 = w04[2];
  w15 = w04[3];
  /* #67: @2 = (@2*@15) */
  w02 *= w15;
  /* #68: (@0[1] += @2) */
  for (rr=w00+1, cs=(&w02); rr!=w00+2; rr+=1) *rr += *cs++;
  /* #69: @2 = -56.8489 */
  w02 = -5.6848921350274701e+01;
  /* #70: @2 = (@2*@14) */
  w02 *= w14;
  /* #71: (@0[0] += @2) */
  for (rr=w00+0, cs=(&w02); rr!=w00+1; rr+=1) *rr += *cs++;
  /* #72: @2 = 0.482549 */
  w02 = 4.8254863159139222e-01;
  /* #73: @2 = (@2*@15) */
  w02 *= w15;
  /* #74: @5 = (@5-@2) */
  w05 -= w02;
  /* #75: (@0[3] += @5) */
  for (rr=w00+3, cs=(&w05); rr!=w00+4; rr+=1) *rr += *cs++;
  /* #76: @5 = 0.120637 */
  w05 = 1.2063715789784805e-01;
  /* #77: @5 = (@5*@14) */
  w05 *= w14;
  /* #78: @3 = (@3-@5) */
  w03 -= w05;
  /* #79: (@0[2] += @3) */
  for (rr=w00+2, cs=(&w03); rr!=w00+3; rr+=1) *rr += *cs++;
  /* #80: output[0][0] = @0 */
  casadi_copy(w00, 4, res[0]);
  /* #81: @3 = 6.28319 */
  w03 = 6.2831853071795862e+00;
  /* #82: @5 = input[2][0] */
  w05 = arg[2] ? arg[2][0] : 0;
  /* #83: @2 = (@3*@5) */
  w02  = (w03*w05);
  /* #84: @16 = sin(@2) */
  w16 = sin( w02 );
  /* #85: @16 = (@16*@7) */
  w16 *= w07;
  /* #86: @17 = 3.14159 */
  w17 = 3.1415926535897931e+00;
  /* #87: @18 = (@17*@5) */
  w18  = (w17*w05);
  /* #88: @19 = sin(@18) */
  w19 = sin( w18 );
  /* #89: @19 = (@19*@6) */
  w19 *= w06;
  /* #90: @16 = (@16+@19) */
  w16 += w19;
  /* #91: @19 = 6.28319 */
  w19 = 6.2831853071795862e+00;
  /* #92: @20 = (@19*@5) */
  w20  = (w19*w05);
  /* #93: @21 = sin(@20) */
  w21 = sin( w20 );
  /* #94: @21 = (@21*@11) */
  w21 *= w11;
  /* #95: @16 = (@16+@21) */
  w16 += w21;
  /* #96: @21 = 3.14159 */
  w21 = 3.1415926535897931e+00;
  /* #97: @22 = (@21*@5) */
  w22  = (w21*w05);
  /* #98: @23 = sin(@22) */
  w23 = sin( w22 );
  /* #99: @23 = (@23*@10) */
  w23 *= w10;
  /* #100: @16 = (@16+@23) */
  w16 += w23;
  /* #101: @23 = 6.28319 */
  w23 = 6.2831853071795862e+00;
  /* #102: @24 = (@23*@5) */
  w24  = (w23*w05);
  /* #103: @25 = sin(@24) */
  w25 = sin( w24 );
  /* #104: @25 = (@25*@13) */
  w25 *= w13;
  /* #105: @16 = (@16+@25) */
  w16 += w25;
  /* #106: @25 = 3.14159 */
  w25 = 3.1415926535897931e+00;
  /* #107: @26 = (@25*@5) */
  w26  = (w25*w05);
  /* #108: @27 = sin(@26) */
  w27 = sin( w26 );
  /* #109: @27 = (@27*@12) */
  w27 *= w12;
  /* #110: @16 = (@16+@27) */
  w16 += w27;
  /* #111: @27 = 6.28319 */
  w27 = 6.2831853071795862e+00;
  /* #112: @28 = (@27*@5) */
  w28  = (w27*w05);
  /* #113: @29 = sin(@28) */
  w29 = sin( w28 );
  /* #114: @29 = (@29*@15) */
  w29 *= w15;
  /* #115: @16 = (@16+@29) */
  w16 += w29;
  /* #116: @29 = 3.14159 */
  w29 = 3.1415926535897931e+00;
  /* #117: @5 = (@29*@5) */
  w05  = (w29*w05);
  /* #118: @30 = sin(@5) */
  w30 = sin( w05 );
  /* #119: @30 = (@30*@14) */
  w30 *= w14;
  /* #120: @16 = (@16+@30) */
  w16 += w30;
  /* #121: output[1][0] = @16 */
  if (res[1]) res[1][0] = w16;
  /* #122: @2 = cos(@2) */
  w02 = cos( w02 );
  /* #123: @16 = input[1][0] */
  w16 = arg[1] ? arg[1][0] : 0;
  /* #124: @7 = (@16*@7) */
  w07  = (w16*w07);
  /* #125: @2 = (@2*@7) */
  w02 *= w07;
  /* #126: @3 = (@3*@2) */
  w03 *= w02;
  /* #127: @18 = cos(@18) */
  w18 = cos( w18 );
  /* #128: @6 = (@16*@6) */
  w06  = (w16*w06);
  /* #129: @18 = (@18*@6) */
  w18 *= w06;
  /* #130: @17 = (@17*@18) */
  w17 *= w18;
  /* #131: @3 = (@3+@17) */
  w03 += w17;
  /* #132: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #133: @11 = (@16*@11) */
  w11  = (w16*w11);
  /* #134: @20 = (@20*@11) */
  w20 *= w11;
  /* #135: @19 = (@19*@20) */
  w19 *= w20;
  /* #136: @3 = (@3+@19) */
  w03 += w19;
  /* #137: @22 = cos(@22) */
  w22 = cos( w22 );
  /* #138: @10 = (@16*@10) */
  w10  = (w16*w10);
  /* #139: @22 = (@22*@10) */
  w22 *= w10;
  /* #140: @21 = (@21*@22) */
  w21 *= w22;
  /* #141: @3 = (@3+@21) */
  w03 += w21;
  /* #142: @24 = cos(@24) */
  w24 = cos( w24 );
  /* #143: @13 = (@16*@13) */
  w13  = (w16*w13);
  /* #144: @24 = (@24*@13) */
  w24 *= w13;
  /* #145: @23 = (@23*@24) */
  w23 *= w24;
  /* #146: @3 = (@3+@23) */
  w03 += w23;
  /* #147: @26 = cos(@26) */
  w26 = cos( w26 );
  /* #148: @12 = (@16*@12) */
  w12  = (w16*w12);
  /* #149: @26 = (@26*@12) */
  w26 *= w12;
  /* #150: @25 = (@25*@26) */
  w25 *= w26;
  /* #151: @3 = (@3+@25) */
  w03 += w25;
  /* #152: @28 = cos(@28) */
  w28 = cos( w28 );
  /* #153: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #154: @28 = (@28*@15) */
  w28 *= w15;
  /* #155: @27 = (@27*@28) */
  w27 *= w28;
  /* #156: @3 = (@3+@27) */
  w03 += w27;
  /* #157: @5 = cos(@5) */
  w05 = cos( w05 );
  /* #158: @16 = (@16*@14) */
  w16 *= w14;
  /* #159: @5 = (@5*@16) */
  w05 *= w16;
  /* #160: @29 = (@29*@5) */
  w29 *= w05;
  /* #161: @3 = (@3+@29) */
  w03 += w29;
  /* #162: output[2][0] = @3 */
  if (res[2]) res[2][0] = w03;
  return 0;
}

/* adj1_step_acc10:(i0[4],i1[1x10],i2[1x10],out_o0[4x10,0nz],adj_o0[4x10])->(adj_i0[4],adj_i1[1x10],adj_i2[1x10]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, *w00=w+46, w01, w02, *w04=w+52, w05, w06, *w08=w+58, w09, w10, *w12=w+64;
  casadi_real w13, w14, *w16=w+70, w17, w18, *w20=w+76, w21, w22, *w24=w+82, w25, w26, *w28=w+88;
  casadi_real w29, w30, *w32=w+94, w33, w34, *w36=w+100, w37, w38, *w41=w+146, *w42=w+150, *w43=w+154, *w44=w+158;
  casadi_real *w45=w+162, *w46=w+166, *w47=w+170, *w48=w+174, *w49=w+178, *w51=w+186, w52, w53;
  const casadi_real **arg1=arg+5, *cs, *wr40, *wr41, *wr42, *wr43, *wr44, *wr45, *wr46, *wr47, *wr48, *wr49;
  const casadi_real *wr50;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 4, w00);
  /* #1: @1 = input[1][0] */
  w01 = arg[1] ? arg[1][0] : 0;
  /* #2: @2 = input[2][0] */
  w02 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = zeros(4x1,0nz) */
  /* #4: @4 = step(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w04;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #5: @5 = input[1][1] */
  w05 = arg[1] ? arg[1][1] : 0;
  /* #6: @6 = input[2][1] */
  w06 = arg[2] ? arg[2][1] : 0;
  /* #7: @7 = zeros(4x1,0nz) */
  /* #8: @8 = step(@4, @5, @6) */
  arg1[0]=w04;
  arg1[1]=(&w05);
  arg1[2]=(&w06);
  res1[0]=w08;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @9 = input[1][2] */
  w09 = arg[1] ? arg[1][2] : 0;
  /* #10: @10 = input[2][2] */
  w10 = arg[2] ? arg[2][2] : 0;
  /* #11: @11 = zeros(4x1,0nz) */
  /* #12: @12 = step(@8, @9, @10) */
  arg1[0]=w08;
  arg1[1]=(&w09);
  arg1[2]=(&w10);
  res1[0]=w12;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @13 = input[1][3] */
  w13 = arg[1] ? arg[1][3] : 0;
  /* #14: @14 = input[2][3] */
  w14 = arg[2] ? arg[2][3] : 0;
  /* #15: @15 = zeros(4x1,0nz) */
  /* #16: @16 = step(@12, @13, @14) */
  arg1[0]=w12;
  arg1[1]=(&w13);
  arg1[2]=(&w14);
  res1[0]=w16;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #17: @17 = input[1][4] */
  w17 = arg[1] ? arg[1][4] : 0;
  /* #18: @18 = input[2][4] */
  w18 = arg[2] ? arg[2][4] : 0;
  /* #19: @19 = zeros(4x1,0nz) */
  /* #20: @20 = step(@16, @17, @18) */
  arg1[0]=w16;
  arg1[1]=(&w17);
  arg1[2]=(&w18);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #21: @21 = input[1][5] */
  w21 = arg[1] ? arg[1][5] : 0;
  /* #22: @22 = input[2][5] */
  w22 = arg[2] ? arg[2][5] : 0;
  /* #23: @23 = zeros(4x1,0nz) */
  /* #24: @24 = step(@20, @21, @22) */
  arg1[0]=w20;
  arg1[1]=(&w21);
  arg1[2]=(&w22);
  res1[0]=w24;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #25: @25 = input[1][6] */
  w25 = arg[1] ? arg[1][6] : 0;
  /* #26: @26 = input[2][6] */
  w26 = arg[2] ? arg[2][6] : 0;
  /* #27: @27 = zeros(4x1,0nz) */
  /* #28: @28 = step(@24, @25, @26) */
  arg1[0]=w24;
  arg1[1]=(&w25);
  arg1[2]=(&w26);
  res1[0]=w28;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #29: @29 = input[1][7] */
  w29 = arg[1] ? arg[1][7] : 0;
  /* #30: @30 = input[2][7] */
  w30 = arg[2] ? arg[2][7] : 0;
  /* #31: @31 = zeros(4x1,0nz) */
  /* #32: @32 = step(@28, @29, @30) */
  arg1[0]=w28;
  arg1[1]=(&w29);
  arg1[2]=(&w30);
  res1[0]=w32;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #33: @33 = input[1][8] */
  w33 = arg[1] ? arg[1][8] : 0;
  /* #34: @34 = input[2][8] */
  w34 = arg[2] ? arg[2][8] : 0;
  /* #35: @35 = zeros(4x1,0nz) */
  /* #36: @36 = step(@32, @33, @34) */
  arg1[0]=w32;
  arg1[1]=(&w33);
  arg1[2]=(&w34);
  res1[0]=w36;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #37: @37 = input[1][9] */
  w37 = arg[1] ? arg[1][9] : 0;
  /* #38: @38 = input[2][9] */
  w38 = arg[2] ? arg[2][9] : 0;
  /* #39: @39 = zeros(4x1,0nz) */
  /* #40: @40 = input[4][0] */
  wr40 = arg[4] ? arg[4] : casadi_zeros;
  /* #41: {@41, @42, @43, @44, @45, @46, @47, @48, @49, @50} = horzsplit(@40) */
  wr41 = wr40;
  wr42 = wr40+4;
  wr43 = wr40+8;
  wr44 = wr40+12;
  wr45 = wr40+16;
  wr46 = wr40+20;
  wr47 = wr40+24;
  wr48 = wr40+28;
  wr49 = wr40+32;
  wr50 = wr40+36;
  /* #42: {@51, @52, @53} = adj1_step(@36, @37, @38, @39, @50) */
  arg1[0]=w36;
  arg1[1]=(&w37);
  arg1[2]=(&w38);
  arg1[3]=0;
  arg1[4]=wr50;
  res1[0]=w51;
  res1[1]=(&w52);
  res1[2]=(&w53);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #43: @51 = (@51+@49) */
  for (i=0, rr=w51, cs=wr49; i<4; ++i) (*rr++) += (*cs++);
  /* #44: {@49, @37, @38} = adj1_step(@32, @33, @34, @35, @51) */
  arg1[0]=w32;
  arg1[1]=(&w33);
  arg1[2]=(&w34);
  arg1[3]=0;
  arg1[4]=w51;
  res1[0]=w49;
  res1[1]=(&w37);
  res1[2]=(&w38);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #45: @49 = (@49+@48) */
  for (i=0, rr=w49, cs=wr48; i<4; ++i) (*rr++) += (*cs++);
  /* #46: {@48, @33, @34} = adj1_step(@28, @29, @30, @31, @49) */
  arg1[0]=w28;
  arg1[1]=(&w29);
  arg1[2]=(&w30);
  arg1[3]=0;
  arg1[4]=w49;
  res1[0]=w48;
  res1[1]=(&w33);
  res1[2]=(&w34);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #47: @48 = (@48+@47) */
  for (i=0, rr=w48, cs=wr47; i<4; ++i) (*rr++) += (*cs++);
  /* #48: {@47, @29, @30} = adj1_step(@24, @25, @26, @27, @48) */
  arg1[0]=w24;
  arg1[1]=(&w25);
  arg1[2]=(&w26);
  arg1[3]=0;
  arg1[4]=w48;
  res1[0]=w47;
  res1[1]=(&w29);
  res1[2]=(&w30);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #49: @47 = (@47+@46) */
  for (i=0, rr=w47, cs=wr46; i<4; ++i) (*rr++) += (*cs++);
  /* #50: {@46, @25, @26} = adj1_step(@20, @21, @22, @23, @47) */
  arg1[0]=w20;
  arg1[1]=(&w21);
  arg1[2]=(&w22);
  arg1[3]=0;
  arg1[4]=w47;
  res1[0]=w46;
  res1[1]=(&w25);
  res1[2]=(&w26);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #51: @46 = (@46+@45) */
  for (i=0, rr=w46, cs=wr45; i<4; ++i) (*rr++) += (*cs++);
  /* #52: {@45, @21, @22} = adj1_step(@16, @17, @18, @19, @46) */
  arg1[0]=w16;
  arg1[1]=(&w17);
  arg1[2]=(&w18);
  arg1[3]=0;
  arg1[4]=w46;
  res1[0]=w45;
  res1[1]=(&w21);
  res1[2]=(&w22);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #53: @45 = (@45+@44) */
  for (i=0, rr=w45, cs=wr44; i<4; ++i) (*rr++) += (*cs++);
  /* #54: {@44, @17, @18} = adj1_step(@12, @13, @14, @15, @45) */
  arg1[0]=w12;
  arg1[1]=(&w13);
  arg1[2]=(&w14);
  arg1[3]=0;
  arg1[4]=w45;
  res1[0]=w44;
  res1[1]=(&w17);
  res1[2]=(&w18);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #55: @44 = (@44+@43) */
  for (i=0, rr=w44, cs=wr43; i<4; ++i) (*rr++) += (*cs++);
  /* #56: {@43, @13, @14} = adj1_step(@8, @9, @10, @11, @44) */
  arg1[0]=w08;
  arg1[1]=(&w09);
  arg1[2]=(&w10);
  arg1[3]=0;
  arg1[4]=w44;
  res1[0]=w43;
  res1[1]=(&w13);
  res1[2]=(&w14);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #57: @43 = (@43+@42) */
  for (i=0, rr=w43, cs=wr42; i<4; ++i) (*rr++) += (*cs++);
  /* #58: {@42, @9, @10} = adj1_step(@4, @5, @6, @7, @43) */
  arg1[0]=w04;
  arg1[1]=(&w05);
  arg1[2]=(&w06);
  arg1[3]=0;
  arg1[4]=w43;
  res1[0]=w42;
  res1[1]=(&w09);
  res1[2]=(&w10);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #59: @42 = (@42+@41) */
  for (i=0, rr=w42, cs=wr41; i<4; ++i) (*rr++) += (*cs++);
  /* #60: {@41, @5, @6} = adj1_step(@0, @1, @2, @3, @42) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w42;
  res1[0]=w41;
  res1[1]=(&w05);
  res1[2]=(&w06);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #61: output[0][0] = @41 */
  casadi_copy(w41, 4, res[0]);
  /* #62: output[1][0] = @5 */
  if (res[1]) res[1][0] = w05;
  /* #63: output[1][1] = @9 */
  if (res[1]) res[1][1] = w09;
  /* #64: output[1][2] = @13 */
  if (res[1]) res[1][2] = w13;
  /* #65: output[1][3] = @17 */
  if (res[1]) res[1][3] = w17;
  /* #66: output[1][4] = @21 */
  if (res[1]) res[1][4] = w21;
  /* #67: output[1][5] = @25 */
  if (res[1]) res[1][5] = w25;
  /* #68: output[1][6] = @29 */
  if (res[1]) res[1][6] = w29;
  /* #69: output[1][7] = @33 */
  if (res[1]) res[1][7] = w33;
  /* #70: output[1][8] = @37 */
  if (res[1]) res[1][8] = w37;
  /* #71: output[1][9] = @52 */
  if (res[1]) res[1][9] = w52;
  /* #72: output[2][0] = @6 */
  if (res[2]) res[2][0] = w06;
  /* #73: output[2][1] = @10 */
  if (res[2]) res[2][1] = w10;
  /* #74: output[2][2] = @14 */
  if (res[2]) res[2][2] = w14;
  /* #75: output[2][3] = @18 */
  if (res[2]) res[2][3] = w18;
  /* #76: output[2][4] = @22 */
  if (res[2]) res[2][4] = w22;
  /* #77: output[2][5] = @26 */
  if (res[2]) res[2][5] = w26;
  /* #78: output[2][6] = @30 */
  if (res[2]) res[2][6] = w30;
  /* #79: output[2][7] = @34 */
  if (res[2]) res[2][7] = w34;
  /* #80: output[2][8] = @38 */
  if (res[2]) res[2][8] = w38;
  /* #81: output[2][9] = @53 */
  if (res[2]) res[2][9] = w53;
  return 0;
}

/* adj1_roll:(i0[4],i1[1x60],i2[1x60],out_o0[4x60,0nz],adj_o0[4x60])->(adj_i0[4],adj_i1[1x60],adj_i2[1x60]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, *w00=w+192, *w05=w+216, *w06=w+256, *w07=w+260, *w08=w+270, *w11=w+280, *w12=w+284, *w13=w+294, *w16=w+304, *w17=w+308;
  casadi_real *w18=w+318, *w21=w+328, *w22=w+332, *w23=w+342, *w26=w+352, *w27=w+356, *w28=w+366, *w35=w+776, *w36=w+816, *w37=w+820, *w38=w+830;
  const casadi_real **arg1=arg+5, *cs, *wr01, *wr02, *wr05, *wr07, *wr08, *wr12, *wr13, *wr17, *wr18, *wr22;
  const casadi_real *wr23, *wr27, *wr28, *wr30, *wr31, *wr32, *wr33, *wr34, *wr35;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 4, w00);
  /* #1: @1 = input[1][0] */
  wr01 = arg[1] ? arg[1] : casadi_zeros;
  /* #2: @2 = input[2][0] */
  wr02 = arg[2] ? arg[2] : casadi_zeros;
  /* #3: @3 = zeros(4x10,0nz) */
  /* #4: @4 = zeros(4x9,0nz) */
  /* #5: @5 = step_acc10(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  res1[0]=w05;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #6: {NULL, @6} = horzsplit(@5) */
  casadi_copy(w05+36, 4, w06);
  /* #7: @7 = input[1][1] */
  wr07 = arg[1] ? arg[1]+10 : casadi_zeros;
  /* #8: @8 = input[2][1] */
  wr08 = arg[2] ? arg[2]+10 : casadi_zeros;
  /* #9: @9 = zeros(4x10,0nz) */
  /* #10: @10 = zeros(4x9,0nz) */
  /* #11: @5 = step_acc10(@6, @7, @8) */
  arg1[0]=w06;
  arg1[1]=wr07;
  arg1[2]=wr08;
  res1[0]=w05;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: {NULL, @11} = horzsplit(@5) */
  casadi_copy(w05+36, 4, w11);
  /* #13: @12 = input[1][2] */
  wr12 = arg[1] ? arg[1]+20 : casadi_zeros;
  /* #14: @13 = input[2][2] */
  wr13 = arg[2] ? arg[2]+20 : casadi_zeros;
  /* #15: @14 = zeros(4x10,0nz) */
  /* #16: @15 = zeros(4x9,0nz) */
  /* #17: @5 = step_acc10(@11, @12, @13) */
  arg1[0]=w11;
  arg1[1]=wr12;
  arg1[2]=wr13;
  res1[0]=w05;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #18: {NULL, @16} = horzsplit(@5) */
  casadi_copy(w05+36, 4, w16);
  /* #19: @17 = input[1][3] */
  wr17 = arg[1] ? arg[1]+30 : casadi_zeros;
  /* #20: @18 = input[2][3] */
  wr18 = arg[2] ? arg[2]+30 : casadi_zeros;
  /* #21: @19 = zeros(4x10,0nz) */
  /* #22: @20 = zeros(4x9,0nz) */
  /* #23: @5 = step_acc10(@16, @17, @18) */
  arg1[0]=w16;
  arg1[1]=wr17;
  arg1[2]=wr18;
  res1[0]=w05;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #24: {NULL, @21} = horzsplit(@5) */
  casadi_copy(w05+36, 4, w21);
  /* #25: @22 = input[1][4] */
  wr22 = arg[1] ? arg[1]+40 : casadi_zeros;
  /* #26: @23 = input[2][4] */
  wr23 = arg[2] ? arg[2]+40 : casadi_zeros;
  /* #27: @24 = zeros(4x10,0nz) */
  /* #28: @25 = zeros(4x9,0nz) */
  /* #29: @5 = step_acc10(@21, @22, @23) */
  arg1[0]=w21;
  arg1[1]=wr22;
  arg1[2]=wr23;
  res1[0]=w05;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #30: {NULL, @26} = horzsplit(@5) */
  casadi_copy(w05+36, 4, w26);
  /* #31: @27 = input[1][5] */
  wr27 = arg[1] ? arg[1]+50 : casadi_zeros;
  /* #32: @28 = input[2][5] */
  wr28 = arg[2] ? arg[2]+50 : casadi_zeros;
  /* #33: @29 = zeros(4x10,0nz) */
  /* #34: @30 = input[4][0] */
  wr30 = arg[4] ? arg[4] : casadi_zeros;
  /* #35: {@5, @31, @32, @33, @34, @35} = horzsplit(@30) */
  wr05 = wr30;
  wr31 = wr30+40;
  wr32 = wr30+80;
  wr33 = wr30+120;
  wr34 = wr30+160;
  wr35 = wr30+200;
  /* #36: {@36, @37, @38} = adj1_step_acc10(@26, @27, @28, @29, @35) */
  arg1[0]=w26;
  arg1[1]=wr27;
  arg1[2]=wr28;
  arg1[3]=0;
  arg1[4]=wr35;
  res1[0]=w36;
  res1[1]=w37;
  res1[2]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #37: @26 = horzcat(@25, @36) */
  rr=w26;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  /* #38: @35 = dense(@26) */
  casadi_densify(w26, casadi_s0, w35, 0);
  /* #39: @35 = (@35+@34) */
  for (i=0, rr=w35, cs=wr34; i<40; ++i) (*rr++) += (*cs++);
  /* #40: {@26, @27, @28} = adj1_step_acc10(@21, @22, @23, @24, @35) */
  arg1[0]=w21;
  arg1[1]=wr22;
  arg1[2]=wr23;
  arg1[3]=0;
  arg1[4]=w35;
  res1[0]=w26;
  res1[1]=w27;
  res1[2]=w28;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #41: @21 = horzcat(@20, @26) */
  rr=w21;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  /* #42: @35 = dense(@21) */
  casadi_densify(w21, casadi_s0, w35, 0);
  /* #43: @35 = (@35+@33) */
  for (i=0, rr=w35, cs=wr33; i<40; ++i) (*rr++) += (*cs++);
  /* #44: {@21, @22, @23} = adj1_step_acc10(@16, @17, @18, @19, @35) */
  arg1[0]=w16;
  arg1[1]=wr17;
  arg1[2]=wr18;
  arg1[3]=0;
  arg1[4]=w35;
  res1[0]=w21;
  res1[1]=w22;
  res1[2]=w23;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #45: @16 = horzcat(@15, @21) */
  rr=w16;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  /* #46: @35 = dense(@16) */
  casadi_densify(w16, casadi_s0, w35, 0);
  /* #47: @35 = (@35+@32) */
  for (i=0, rr=w35, cs=wr32; i<40; ++i) (*rr++) += (*cs++);
  /* #48: {@16, @17, @18} = adj1_step_acc10(@11, @12, @13, @14, @35) */
  arg1[0]=w11;
  arg1[1]=wr12;
  arg1[2]=wr13;
  arg1[3]=0;
  arg1[4]=w35;
  res1[0]=w16;
  res1[1]=w17;
  res1[2]=w18;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #49: @11 = horzcat(@10, @16) */
  rr=w11;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #50: @35 = dense(@11) */
  casadi_densify(w11, casadi_s0, w35, 0);
  /* #51: @35 = (@35+@31) */
  for (i=0, rr=w35, cs=wr31; i<40; ++i) (*rr++) += (*cs++);
  /* #52: {@11, @12, @13} = adj1_step_acc10(@6, @7, @8, @9, @35) */
  arg1[0]=w06;
  arg1[1]=wr07;
  arg1[2]=wr08;
  arg1[3]=0;
  arg1[4]=w35;
  res1[0]=w11;
  res1[1]=w12;
  res1[2]=w13;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #53: @6 = horzcat(@4, @11) */
  rr=w06;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #54: @35 = dense(@6) */
  casadi_densify(w06, casadi_s0, w35, 0);
  /* #55: @35 = (@35+@5) */
  for (i=0, rr=w35, cs=wr05; i<40; ++i) (*rr++) += (*cs++);
  /* #56: {@6, @7, @8} = adj1_step_acc10(@0, @1, @2, @3, @35) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  arg1[3]=0;
  arg1[4]=w35;
  res1[0]=w06;
  res1[1]=w07;
  res1[2]=w08;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #57: output[0][0] = @6 */
  casadi_copy(w06, 4, res[0]);
  /* #58: output[1][0] = @7 */
  casadi_copy(w07, 10, res[1]);
  /* #59: output[1][1] = @12 */
  if (res[1]) casadi_copy(w12, 10, res[1]+10);
  /* #60: output[1][2] = @17 */
  if (res[1]) casadi_copy(w17, 10, res[1]+20);
  /* #61: output[1][3] = @22 */
  if (res[1]) casadi_copy(w22, 10, res[1]+30);
  /* #62: output[1][4] = @27 */
  if (res[1]) casadi_copy(w27, 10, res[1]+40);
  /* #63: output[1][5] = @37 */
  if (res[1]) casadi_copy(w37, 10, res[1]+50);
  /* #64: output[2][0] = @8 */
  casadi_copy(w08, 10, res[2]);
  /* #65: output[2][1] = @13 */
  if (res[2]) casadi_copy(w13, 10, res[2]+10);
  /* #66: output[2][2] = @18 */
  if (res[2]) casadi_copy(w18, 10, res[2]+20);
  /* #67: output[2][3] = @23 */
  if (res[2]) casadi_copy(w23, 10, res[2]+30);
  /* #68: output[2][4] = @28 */
  if (res[2]) casadi_copy(w28, 10, res[2]+40);
  /* #69: output[2][5] = @38 */
  if (res[2]) casadi_copy(w38, 10, res[2]+50);
  return 0;
}

/* F_ej_p:(i0[60],i1)->(o0,o1[1x60]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+2, *rr, *w00=w+840, *w01=w+844, w03, *w04=w+909, *w05=w+969, *w06=w+1209, *w07=w+1453, *w08=w+1697, *w10=w+1757;
  const casadi_real **arg1=arg+2, *cs, *wr02;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w00, 4);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w01, 4);
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @2 = @2' */
  /* #4: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #5: @4 = repmat(@3, 60) */
  for (i=0;i<60;++i) {
    casadi_copy((&w03), 1, w04+ i*1);
  }
  /* #6: @5 = roll(@1, @2, @4) */
  arg1[0]=w01;
  arg1[1]=wr02;
  arg1[2]=w04;
  res1[0]=w05;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @6 = horzcat(@0, @5) */
  rr=w06;
  for (i=0, cs=w00; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w05; i<240; ++i) *rr++ = *cs++;
  /* #8: @7 = @6' */
  for (i=0, rr=w07, cs=w06; i<61; ++i) for (j=0; j<4; ++j) rr[i+j*61] = *cs++;
  /* #9: @3 = @7[243] */
  for (rr=(&w03), cs=w07+243; cs!=w07+244; cs+=1) *rr++ = *cs;
  /* #10: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #11: @8 = zeros(60x1) */
  casadi_clear(w08, 60);
  /* #12: @9 = zeros(4x60,0nz) */
  /* #13: @7 = zeros(61x4) */
  casadi_clear(w07, 244);
  /* #14: @3 = 1 */
  w03 = 1.;
  /* #15: (@7[243] += @3) */
  for (rr=w07+243, cs=(&w03); rr!=w07+244; rr+=1) *rr += *cs++;
  /* #16: @6 = @7' */
  for (i=0, rr=w06, cs=w07; i<4; ++i) for (j=0; j<61; ++j) rr[i+j*4] = *cs++;
  /* #17: {NULL, @5} = horzsplit(@6) */
  casadi_copy(w06+4, 240, w05);
  /* #18: {NULL, @10, NULL} = adj1_roll(@1, @2, @4, @9, @5) */
  arg1[0]=w01;
  arg1[1]=wr02;
  arg1[2]=w04;
  arg1[3]=0;
  arg1[4]=w05;
  res1[0]=0;
  res1[1]=w10;
  res1[2]=0;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #19: @10 = @10' */
  /* #20: @3 = @10[0] */
  for (rr=(&w03), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #21: (@8[0] = @3) */
  for (rr=w08+0, cs=(&w03); rr!=w08+1; rr+=1) *rr = *cs++;
  /* #22: @3 = @10[1] */
  for (rr=(&w03), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #23: (@8[1] = @3) */
  for (rr=w08+1, cs=(&w03); rr!=w08+2; rr+=1) *rr = *cs++;
  /* #24: @3 = @10[2] */
  for (rr=(&w03), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #25: (@8[2] = @3) */
  for (rr=w08+2, cs=(&w03); rr!=w08+3; rr+=1) *rr = *cs++;
  /* #26: @3 = @10[3] */
  for (rr=(&w03), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #27: (@8[3] = @3) */
  for (rr=w08+3, cs=(&w03); rr!=w08+4; rr+=1) *rr = *cs++;
  /* #28: @3 = @10[4] */
  for (rr=(&w03), cs=w10+4; cs!=w10+5; cs+=1) *rr++ = *cs;
  /* #29: (@8[4] = @3) */
  for (rr=w08+4, cs=(&w03); rr!=w08+5; rr+=1) *rr = *cs++;
  /* #30: @3 = @10[5] */
  for (rr=(&w03), cs=w10+5; cs!=w10+6; cs+=1) *rr++ = *cs;
  /* #31: (@8[5] = @3) */
  for (rr=w08+5, cs=(&w03); rr!=w08+6; rr+=1) *rr = *cs++;
  /* #32: @3 = @10[6] */
  for (rr=(&w03), cs=w10+6; cs!=w10+7; cs+=1) *rr++ = *cs;
  /* #33: (@8[6] = @3) */
  for (rr=w08+6, cs=(&w03); rr!=w08+7; rr+=1) *rr = *cs++;
  /* #34: @3 = @10[7] */
  for (rr=(&w03), cs=w10+7; cs!=w10+8; cs+=1) *rr++ = *cs;
  /* #35: (@8[7] = @3) */
  for (rr=w08+7, cs=(&w03); rr!=w08+8; rr+=1) *rr = *cs++;
  /* #36: @3 = @10[8] */
  for (rr=(&w03), cs=w10+8; cs!=w10+9; cs+=1) *rr++ = *cs;
  /* #37: (@8[8] = @3) */
  for (rr=w08+8, cs=(&w03); rr!=w08+9; rr+=1) *rr = *cs++;
  /* #38: @3 = @10[9] */
  for (rr=(&w03), cs=w10+9; cs!=w10+10; cs+=1) *rr++ = *cs;
  /* #39: (@8[9] = @3) */
  for (rr=w08+9, cs=(&w03); rr!=w08+10; rr+=1) *rr = *cs++;
  /* #40: @3 = @10[10] */
  for (rr=(&w03), cs=w10+10; cs!=w10+11; cs+=1) *rr++ = *cs;
  /* #41: (@8[10] = @3) */
  for (rr=w08+10, cs=(&w03); rr!=w08+11; rr+=1) *rr = *cs++;
  /* #42: @3 = @10[11] */
  for (rr=(&w03), cs=w10+11; cs!=w10+12; cs+=1) *rr++ = *cs;
  /* #43: (@8[11] = @3) */
  for (rr=w08+11, cs=(&w03); rr!=w08+12; rr+=1) *rr = *cs++;
  /* #44: @3 = @10[12] */
  for (rr=(&w03), cs=w10+12; cs!=w10+13; cs+=1) *rr++ = *cs;
  /* #45: (@8[12] = @3) */
  for (rr=w08+12, cs=(&w03); rr!=w08+13; rr+=1) *rr = *cs++;
  /* #46: @3 = @10[13] */
  for (rr=(&w03), cs=w10+13; cs!=w10+14; cs+=1) *rr++ = *cs;
  /* #47: (@8[13] = @3) */
  for (rr=w08+13, cs=(&w03); rr!=w08+14; rr+=1) *rr = *cs++;
  /* #48: @3 = @10[14] */
  for (rr=(&w03), cs=w10+14; cs!=w10+15; cs+=1) *rr++ = *cs;
  /* #49: (@8[14] = @3) */
  for (rr=w08+14, cs=(&w03); rr!=w08+15; rr+=1) *rr = *cs++;
  /* #50: @3 = @10[15] */
  for (rr=(&w03), cs=w10+15; cs!=w10+16; cs+=1) *rr++ = *cs;
  /* #51: (@8[15] = @3) */
  for (rr=w08+15, cs=(&w03); rr!=w08+16; rr+=1) *rr = *cs++;
  /* #52: @3 = @10[16] */
  for (rr=(&w03), cs=w10+16; cs!=w10+17; cs+=1) *rr++ = *cs;
  /* #53: (@8[16] = @3) */
  for (rr=w08+16, cs=(&w03); rr!=w08+17; rr+=1) *rr = *cs++;
  /* #54: @3 = @10[17] */
  for (rr=(&w03), cs=w10+17; cs!=w10+18; cs+=1) *rr++ = *cs;
  /* #55: (@8[17] = @3) */
  for (rr=w08+17, cs=(&w03); rr!=w08+18; rr+=1) *rr = *cs++;
  /* #56: @3 = @10[18] */
  for (rr=(&w03), cs=w10+18; cs!=w10+19; cs+=1) *rr++ = *cs;
  /* #57: (@8[18] = @3) */
  for (rr=w08+18, cs=(&w03); rr!=w08+19; rr+=1) *rr = *cs++;
  /* #58: @3 = @10[19] */
  for (rr=(&w03), cs=w10+19; cs!=w10+20; cs+=1) *rr++ = *cs;
  /* #59: (@8[19] = @3) */
  for (rr=w08+19, cs=(&w03); rr!=w08+20; rr+=1) *rr = *cs++;
  /* #60: @3 = @10[20] */
  for (rr=(&w03), cs=w10+20; cs!=w10+21; cs+=1) *rr++ = *cs;
  /* #61: (@8[20] = @3) */
  for (rr=w08+20, cs=(&w03); rr!=w08+21; rr+=1) *rr = *cs++;
  /* #62: @3 = @10[21] */
  for (rr=(&w03), cs=w10+21; cs!=w10+22; cs+=1) *rr++ = *cs;
  /* #63: (@8[21] = @3) */
  for (rr=w08+21, cs=(&w03); rr!=w08+22; rr+=1) *rr = *cs++;
  /* #64: @3 = @10[22] */
  for (rr=(&w03), cs=w10+22; cs!=w10+23; cs+=1) *rr++ = *cs;
  /* #65: (@8[22] = @3) */
  for (rr=w08+22, cs=(&w03); rr!=w08+23; rr+=1) *rr = *cs++;
  /* #66: @3 = @10[23] */
  for (rr=(&w03), cs=w10+23; cs!=w10+24; cs+=1) *rr++ = *cs;
  /* #67: (@8[23] = @3) */
  for (rr=w08+23, cs=(&w03); rr!=w08+24; rr+=1) *rr = *cs++;
  /* #68: @3 = @10[24] */
  for (rr=(&w03), cs=w10+24; cs!=w10+25; cs+=1) *rr++ = *cs;
  /* #69: (@8[24] = @3) */
  for (rr=w08+24, cs=(&w03); rr!=w08+25; rr+=1) *rr = *cs++;
  /* #70: @3 = @10[25] */
  for (rr=(&w03), cs=w10+25; cs!=w10+26; cs+=1) *rr++ = *cs;
  /* #71: (@8[25] = @3) */
  for (rr=w08+25, cs=(&w03); rr!=w08+26; rr+=1) *rr = *cs++;
  /* #72: @3 = @10[26] */
  for (rr=(&w03), cs=w10+26; cs!=w10+27; cs+=1) *rr++ = *cs;
  /* #73: (@8[26] = @3) */
  for (rr=w08+26, cs=(&w03); rr!=w08+27; rr+=1) *rr = *cs++;
  /* #74: @3 = @10[27] */
  for (rr=(&w03), cs=w10+27; cs!=w10+28; cs+=1) *rr++ = *cs;
  /* #75: (@8[27] = @3) */
  for (rr=w08+27, cs=(&w03); rr!=w08+28; rr+=1) *rr = *cs++;
  /* #76: @3 = @10[28] */
  for (rr=(&w03), cs=w10+28; cs!=w10+29; cs+=1) *rr++ = *cs;
  /* #77: (@8[28] = @3) */
  for (rr=w08+28, cs=(&w03); rr!=w08+29; rr+=1) *rr = *cs++;
  /* #78: @3 = @10[29] */
  for (rr=(&w03), cs=w10+29; cs!=w10+30; cs+=1) *rr++ = *cs;
  /* #79: (@8[29] = @3) */
  for (rr=w08+29, cs=(&w03); rr!=w08+30; rr+=1) *rr = *cs++;
  /* #80: @3 = @10[30] */
  for (rr=(&w03), cs=w10+30; cs!=w10+31; cs+=1) *rr++ = *cs;
  /* #81: (@8[30] = @3) */
  for (rr=w08+30, cs=(&w03); rr!=w08+31; rr+=1) *rr = *cs++;
  /* #82: @3 = @10[31] */
  for (rr=(&w03), cs=w10+31; cs!=w10+32; cs+=1) *rr++ = *cs;
  /* #83: (@8[31] = @3) */
  for (rr=w08+31, cs=(&w03); rr!=w08+32; rr+=1) *rr = *cs++;
  /* #84: @3 = @10[32] */
  for (rr=(&w03), cs=w10+32; cs!=w10+33; cs+=1) *rr++ = *cs;
  /* #85: (@8[32] = @3) */
  for (rr=w08+32, cs=(&w03); rr!=w08+33; rr+=1) *rr = *cs++;
  /* #86: @3 = @10[33] */
  for (rr=(&w03), cs=w10+33; cs!=w10+34; cs+=1) *rr++ = *cs;
  /* #87: (@8[33] = @3) */
  for (rr=w08+33, cs=(&w03); rr!=w08+34; rr+=1) *rr = *cs++;
  /* #88: @3 = @10[34] */
  for (rr=(&w03), cs=w10+34; cs!=w10+35; cs+=1) *rr++ = *cs;
  /* #89: (@8[34] = @3) */
  for (rr=w08+34, cs=(&w03); rr!=w08+35; rr+=1) *rr = *cs++;
  /* #90: @3 = @10[35] */
  for (rr=(&w03), cs=w10+35; cs!=w10+36; cs+=1) *rr++ = *cs;
  /* #91: (@8[35] = @3) */
  for (rr=w08+35, cs=(&w03); rr!=w08+36; rr+=1) *rr = *cs++;
  /* #92: @3 = @10[36] */
  for (rr=(&w03), cs=w10+36; cs!=w10+37; cs+=1) *rr++ = *cs;
  /* #93: (@8[36] = @3) */
  for (rr=w08+36, cs=(&w03); rr!=w08+37; rr+=1) *rr = *cs++;
  /* #94: @3 = @10[37] */
  for (rr=(&w03), cs=w10+37; cs!=w10+38; cs+=1) *rr++ = *cs;
  /* #95: (@8[37] = @3) */
  for (rr=w08+37, cs=(&w03); rr!=w08+38; rr+=1) *rr = *cs++;
  /* #96: @3 = @10[38] */
  for (rr=(&w03), cs=w10+38; cs!=w10+39; cs+=1) *rr++ = *cs;
  /* #97: (@8[38] = @3) */
  for (rr=w08+38, cs=(&w03); rr!=w08+39; rr+=1) *rr = *cs++;
  /* #98: @3 = @10[39] */
  for (rr=(&w03), cs=w10+39; cs!=w10+40; cs+=1) *rr++ = *cs;
  /* #99: (@8[39] = @3) */
  for (rr=w08+39, cs=(&w03); rr!=w08+40; rr+=1) *rr = *cs++;
  /* #100: @3 = @10[40] */
  for (rr=(&w03), cs=w10+40; cs!=w10+41; cs+=1) *rr++ = *cs;
  /* #101: (@8[40] = @3) */
  for (rr=w08+40, cs=(&w03); rr!=w08+41; rr+=1) *rr = *cs++;
  /* #102: @3 = @10[41] */
  for (rr=(&w03), cs=w10+41; cs!=w10+42; cs+=1) *rr++ = *cs;
  /* #103: (@8[41] = @3) */
  for (rr=w08+41, cs=(&w03); rr!=w08+42; rr+=1) *rr = *cs++;
  /* #104: @3 = @10[42] */
  for (rr=(&w03), cs=w10+42; cs!=w10+43; cs+=1) *rr++ = *cs;
  /* #105: (@8[42] = @3) */
  for (rr=w08+42, cs=(&w03); rr!=w08+43; rr+=1) *rr = *cs++;
  /* #106: @3 = @10[43] */
  for (rr=(&w03), cs=w10+43; cs!=w10+44; cs+=1) *rr++ = *cs;
  /* #107: (@8[43] = @3) */
  for (rr=w08+43, cs=(&w03); rr!=w08+44; rr+=1) *rr = *cs++;
  /* #108: @3 = @10[44] */
  for (rr=(&w03), cs=w10+44; cs!=w10+45; cs+=1) *rr++ = *cs;
  /* #109: (@8[44] = @3) */
  for (rr=w08+44, cs=(&w03); rr!=w08+45; rr+=1) *rr = *cs++;
  /* #110: @3 = @10[45] */
  for (rr=(&w03), cs=w10+45; cs!=w10+46; cs+=1) *rr++ = *cs;
  /* #111: (@8[45] = @3) */
  for (rr=w08+45, cs=(&w03); rr!=w08+46; rr+=1) *rr = *cs++;
  /* #112: @3 = @10[46] */
  for (rr=(&w03), cs=w10+46; cs!=w10+47; cs+=1) *rr++ = *cs;
  /* #113: (@8[46] = @3) */
  for (rr=w08+46, cs=(&w03); rr!=w08+47; rr+=1) *rr = *cs++;
  /* #114: @3 = @10[47] */
  for (rr=(&w03), cs=w10+47; cs!=w10+48; cs+=1) *rr++ = *cs;
  /* #115: (@8[47] = @3) */
  for (rr=w08+47, cs=(&w03); rr!=w08+48; rr+=1) *rr = *cs++;
  /* #116: @3 = @10[48] */
  for (rr=(&w03), cs=w10+48; cs!=w10+49; cs+=1) *rr++ = *cs;
  /* #117: (@8[48] = @3) */
  for (rr=w08+48, cs=(&w03); rr!=w08+49; rr+=1) *rr = *cs++;
  /* #118: @3 = @10[49] */
  for (rr=(&w03), cs=w10+49; cs!=w10+50; cs+=1) *rr++ = *cs;
  /* #119: (@8[49] = @3) */
  for (rr=w08+49, cs=(&w03); rr!=w08+50; rr+=1) *rr = *cs++;
  /* #120: @3 = @10[50] */
  for (rr=(&w03), cs=w10+50; cs!=w10+51; cs+=1) *rr++ = *cs;
  /* #121: (@8[50] = @3) */
  for (rr=w08+50, cs=(&w03); rr!=w08+51; rr+=1) *rr = *cs++;
  /* #122: @3 = @10[51] */
  for (rr=(&w03), cs=w10+51; cs!=w10+52; cs+=1) *rr++ = *cs;
  /* #123: (@8[51] = @3) */
  for (rr=w08+51, cs=(&w03); rr!=w08+52; rr+=1) *rr = *cs++;
  /* #124: @3 = @10[52] */
  for (rr=(&w03), cs=w10+52; cs!=w10+53; cs+=1) *rr++ = *cs;
  /* #125: (@8[52] = @3) */
  for (rr=w08+52, cs=(&w03); rr!=w08+53; rr+=1) *rr = *cs++;
  /* #126: @3 = @10[53] */
  for (rr=(&w03), cs=w10+53; cs!=w10+54; cs+=1) *rr++ = *cs;
  /* #127: (@8[53] = @3) */
  for (rr=w08+53, cs=(&w03); rr!=w08+54; rr+=1) *rr = *cs++;
  /* #128: @3 = @10[54] */
  for (rr=(&w03), cs=w10+54; cs!=w10+55; cs+=1) *rr++ = *cs;
  /* #129: (@8[54] = @3) */
  for (rr=w08+54, cs=(&w03); rr!=w08+55; rr+=1) *rr = *cs++;
  /* #130: @3 = @10[55] */
  for (rr=(&w03), cs=w10+55; cs!=w10+56; cs+=1) *rr++ = *cs;
  /* #131: (@8[55] = @3) */
  for (rr=w08+55, cs=(&w03); rr!=w08+56; rr+=1) *rr = *cs++;
  /* #132: @3 = @10[56] */
  for (rr=(&w03), cs=w10+56; cs!=w10+57; cs+=1) *rr++ = *cs;
  /* #133: (@8[56] = @3) */
  for (rr=w08+56, cs=(&w03); rr!=w08+57; rr+=1) *rr = *cs++;
  /* #134: @3 = @10[57] */
  for (rr=(&w03), cs=w10+57; cs!=w10+58; cs+=1) *rr++ = *cs;
  /* #135: (@8[57] = @3) */
  for (rr=w08+57, cs=(&w03); rr!=w08+58; rr+=1) *rr = *cs++;
  /* #136: @3 = @10[58] */
  for (rr=(&w03), cs=w10+58; cs!=w10+59; cs+=1) *rr++ = *cs;
  /* #137: (@8[58] = @3) */
  for (rr=w08+58, cs=(&w03); rr!=w08+59; rr+=1) *rr = *cs++;
  /* #138: @3 = @10[59] */
  for (rr=(&w03), cs=w10+59; cs!=w10+60; cs+=1) *rr++ = *cs;
  /* #139: (@8[59] = @3) */
  for (rr=w08+59, cs=(&w03); rr!=w08+60; rr+=1) *rr = *cs++;
  /* #140: output[1][0] = @8 */
  casadi_copy(w08, 60, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int F_ej_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_ej_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_ej_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_ej_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_ej_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_ej_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_ej_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_ej_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_ej_p_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_ej_p_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real F_ej_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_ej_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_ej_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_ej_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_ej_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_ej_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1817;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_ej_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 1817*sizeof(casadi_real);
  return 0;
}

/* F_end_p:(i0[60],i1)->(o0) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+1, *rr, *w0=w+98, *w1=w+102, w3, *w4=w+167, *w5=w+227, *w6=w+467, *w7=w+711;
  const casadi_real **arg1=arg+2, *cs, *wr2;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[0][0] */
  wr2 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @2 = @2' */
  /* #4: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #5: @4 = repmat(@3, 60) */
  for (i=0;i<60;++i) {
    casadi_copy((&w3), 1, w4+ i*1);
  }
  /* #6: @5 = roll(@1, @2, @4) */
  arg1[0]=w1;
  arg1[1]=wr2;
  arg1[2]=w4;
  res1[0]=w5;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @6 = horzcat(@0, @5) */
  rr=w6;
  for (i=0, cs=w0; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<240; ++i) *rr++ = *cs++;
  /* #8: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<61; ++i) for (j=0; j<4; ++j) rr[i+j*61] = *cs++;
  /* #9: @3 = @7[243] */
  for (rr=(&w3), cs=w7+243; cs!=w7+244; cs+=1) *rr++ = *cs;
  /* #10: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_end_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_end_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_end_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_end_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_end_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_end_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_end_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_end_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_end_p_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_end_p_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_end_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_end_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_end_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_end_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_end_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_end_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 955;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_end_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 955*sizeof(casadi_real);
  return 0;
}

/* fwd1_step:(i0[4],i1,i2,out_o0[4x1,0nz],fwd_i0[4],fwd_i1,fwd_i2)->(fwd_o0[4]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, *w13=w+16, *w14=w+20, *w15=w+24;
  const casadi_real *cr, *cs;
  /* #0: @0 = input[4][0] */
  casadi_copy(arg[4], 4, w00);
  /* #1: @1 = 0.00166667 */
  w01 = 1.6666666666666668e-03;
  /* #2: @2 = @0[2] */
  for (rr=(&w02), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #3: @3 = @0[3] */
  for (rr=(&w03), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #4: @4 = -56.8489 */
  w04 = -5.6848921350274701e+01;
  /* #5: @5 = @0[0] */
  for (rr=(&w05), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #6: @4 = (@4*@5) */
  w04 *= w05;
  /* #7: @5 = 0.120637 */
  w05 = 1.2063715789784805e-01;
  /* #8: @5 = (@5*@2) */
  w05 *= w02;
  /* #9: @4 = (@4-@5) */
  w04 -= w05;
  /* #10: @5 = input[1][0] */
  w05 = arg[1] ? arg[1][0] : 0;
  /* #11: @6 = 3.14159 */
  w06 = 3.1415926535897931e+00;
  /* #12: @7 = input[2][0] */
  w07 = arg[2] ? arg[2][0] : 0;
  /* #13: @8 = (@6*@7) */
  w08  = (w06*w07);
  /* #14: @9 = cos(@8) */
  w09 = cos( w08 );
  /* #15: @10 = input[6][0] */
  w10 = arg[6] ? arg[6][0] : 0;
  /* #16: @6 = (@6*@10) */
  w06 *= w10;
  /* #17: @9 = (@9*@6) */
  w09 *= w06;
  /* #18: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #19: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #20: @6 = input[5][0] */
  w06 = arg[5] ? arg[5][0] : 0;
  /* #21: @8 = (@8*@6) */
  w08 *= w06;
  /* #22: @9 = (@9+@8) */
  w09 += w08;
  /* #23: @4 = (@4+@9) */
  w04 += w09;
  /* #24: @9 = -909.583 */
  w09 = -9.0958274160439521e+02;
  /* #25: @8 = @0[1] */
  for (rr=(&w08), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #26: @9 = (@9*@8) */
  w09 *= w08;
  /* #27: @8 = 0.482549 */
  w08 = 4.8254863159139222e-01;
  /* #28: @8 = (@8*@3) */
  w08 *= w03;
  /* #29: @9 = (@9-@8) */
  w09 -= w08;
  /* #30: @8 = 6.28319 */
  w08 = 6.2831853071795862e+00;
  /* #31: @11 = (@8*@7) */
  w11  = (w08*w07);
  /* #32: @12 = cos(@11) */
  w12 = cos( w11 );
  /* #33: @8 = (@8*@10) */
  w08 *= w10;
  /* #34: @12 = (@12*@8) */
  w12 *= w08;
  /* #35: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #36: @11 = sin(@11) */
  w11 = sin( w11 );
  /* #37: @11 = (@11*@6) */
  w11 *= w06;
  /* #38: @12 = (@12+@11) */
  w12 += w11;
  /* #39: @9 = (@9+@12) */
  w09 += w12;
  /* #40: @13 = vertcat(@2, @3, @4, @9) */
  rr=w13;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  /* #41: @2 = 0.005 */
  w02 = 5.0000000000000001e-03;
  /* #42: @14 = (@2*@13) */
  for (i=0, rr=w14, cs=w13; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #43: @14 = (@0+@14) */
  for (i=0, rr=w14, cr=w00, cs=w14; i<4; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #44: @2 = @14[2] */
  for (rr=(&w02), cs=w14+2; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #45: @3 = @14[3] */
  for (rr=(&w03), cs=w14+3; cs!=w14+4; cs+=1) *rr++ = *cs;
  /* #46: @4 = -56.8489 */
  w04 = -5.6848921350274701e+01;
  /* #47: @9 = @14[0] */
  for (rr=(&w09), cs=w14+0; cs!=w14+1; cs+=1) *rr++ = *cs;
  /* #48: @4 = (@4*@9) */
  w04 *= w09;
  /* #49: @9 = 0.120637 */
  w09 = 1.2063715789784805e-01;
  /* #50: @9 = (@9*@2) */
  w09 *= w02;
  /* #51: @4 = (@4-@9) */
  w04 -= w09;
  /* #52: @9 = 3.14159 */
  w09 = 3.1415926535897931e+00;
  /* #53: @12 = (@9*@7) */
  w12  = (w09*w07);
  /* #54: @11 = cos(@12) */
  w11 = cos( w12 );
  /* #55: @9 = (@9*@10) */
  w09 *= w10;
  /* #56: @11 = (@11*@9) */
  w11 *= w09;
  /* #57: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #58: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #59: @12 = (@12*@6) */
  w12 *= w06;
  /* #60: @11 = (@11+@12) */
  w11 += w12;
  /* #61: @4 = (@4+@11) */
  w04 += w11;
  /* #62: @11 = -909.583 */
  w11 = -9.0958274160439521e+02;
  /* #63: @12 = @14[1] */
  for (rr=(&w12), cs=w14+1; cs!=w14+2; cs+=1) *rr++ = *cs;
  /* #64: @11 = (@11*@12) */
  w11 *= w12;
  /* #65: @12 = 0.482549 */
  w12 = 4.8254863159139222e-01;
  /* #66: @12 = (@12*@3) */
  w12 *= w03;
  /* #67: @11 = (@11-@12) */
  w11 -= w12;
  /* #68: @12 = 6.28319 */
  w12 = 6.2831853071795862e+00;
  /* #69: @9 = (@12*@7) */
  w09  = (w12*w07);
  /* #70: @8 = cos(@9) */
  w08 = cos( w09 );
  /* #71: @12 = (@12*@10) */
  w12 *= w10;
  /* #72: @8 = (@8*@12) */
  w08 *= w12;
  /* #73: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #74: @9 = sin(@9) */
  w09 = sin( w09 );
  /* #75: @9 = (@9*@6) */
  w09 *= w06;
  /* #76: @8 = (@8+@9) */
  w08 += w09;
  /* #77: @11 = (@11+@8) */
  w11 += w08;
  /* #78: @14 = vertcat(@2, @3, @4, @11) */
  rr=w14;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w11;
  /* #79: @15 = (2.*@14) */
  for (i=0, rr=w15, cs=w14; i<4; ++i) *rr++ = (2.* *cs++ );
  /* #80: @13 = (@13+@15) */
  for (i=0, rr=w13, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #81: @2 = 0.005 */
  w02 = 5.0000000000000001e-03;
  /* #82: @14 = (@2*@14) */
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #83: @14 = (@0+@14) */
  for (i=0, rr=w14, cr=w00, cs=w14; i<4; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #84: @2 = @14[2] */
  for (rr=(&w02), cs=w14+2; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #85: @3 = @14[3] */
  for (rr=(&w03), cs=w14+3; cs!=w14+4; cs+=1) *rr++ = *cs;
  /* #86: @4 = -56.8489 */
  w04 = -5.6848921350274701e+01;
  /* #87: @11 = @14[0] */
  for (rr=(&w11), cs=w14+0; cs!=w14+1; cs+=1) *rr++ = *cs;
  /* #88: @4 = (@4*@11) */
  w04 *= w11;
  /* #89: @11 = 0.120637 */
  w11 = 1.2063715789784805e-01;
  /* #90: @11 = (@11*@2) */
  w11 *= w02;
  /* #91: @4 = (@4-@11) */
  w04 -= w11;
  /* #92: @11 = 3.14159 */
  w11 = 3.1415926535897931e+00;
  /* #93: @8 = (@11*@7) */
  w08  = (w11*w07);
  /* #94: @9 = cos(@8) */
  w09 = cos( w08 );
  /* #95: @11 = (@11*@10) */
  w11 *= w10;
  /* #96: @9 = (@9*@11) */
  w09 *= w11;
  /* #97: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #98: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #99: @8 = (@8*@6) */
  w08 *= w06;
  /* #100: @9 = (@9+@8) */
  w09 += w08;
  /* #101: @4 = (@4+@9) */
  w04 += w09;
  /* #102: @9 = -909.583 */
  w09 = -9.0958274160439521e+02;
  /* #103: @8 = @14[1] */
  for (rr=(&w08), cs=w14+1; cs!=w14+2; cs+=1) *rr++ = *cs;
  /* #104: @9 = (@9*@8) */
  w09 *= w08;
  /* #105: @8 = 0.482549 */
  w08 = 4.8254863159139222e-01;
  /* #106: @8 = (@8*@3) */
  w08 *= w03;
  /* #107: @9 = (@9-@8) */
  w09 -= w08;
  /* #108: @8 = 6.28319 */
  w08 = 6.2831853071795862e+00;
  /* #109: @11 = (@8*@7) */
  w11  = (w08*w07);
  /* #110: @12 = cos(@11) */
  w12 = cos( w11 );
  /* #111: @8 = (@8*@10) */
  w08 *= w10;
  /* #112: @12 = (@12*@8) */
  w12 *= w08;
  /* #113: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #114: @11 = sin(@11) */
  w11 = sin( w11 );
  /* #115: @11 = (@11*@6) */
  w11 *= w06;
  /* #116: @12 = (@12+@11) */
  w12 += w11;
  /* #117: @9 = (@9+@12) */
  w09 += w12;
  /* #118: @14 = vertcat(@2, @3, @4, @9) */
  rr=w14;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  /* #119: @15 = (2.*@14) */
  for (i=0, rr=w15, cs=w14; i<4; ++i) *rr++ = (2.* *cs++ );
  /* #120: @13 = (@13+@15) */
  for (i=0, rr=w13, cs=w15; i<4; ++i) (*rr++) += (*cs++);
  /* #121: @2 = 0.01 */
  w02 = 1.0000000000000000e-02;
  /* #122: @14 = (@2*@14) */
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #123: @14 = (@0+@14) */
  for (i=0, rr=w14, cr=w00, cs=w14; i<4; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #124: @2 = @14[2] */
  for (rr=(&w02), cs=w14+2; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #125: @3 = @14[3] */
  for (rr=(&w03), cs=w14+3; cs!=w14+4; cs+=1) *rr++ = *cs;
  /* #126: @4 = -56.8489 */
  w04 = -5.6848921350274701e+01;
  /* #127: @9 = @14[0] */
  for (rr=(&w09), cs=w14+0; cs!=w14+1; cs+=1) *rr++ = *cs;
  /* #128: @4 = (@4*@9) */
  w04 *= w09;
  /* #129: @9 = 0.120637 */
  w09 = 1.2063715789784805e-01;
  /* #130: @9 = (@9*@2) */
  w09 *= w02;
  /* #131: @4 = (@4-@9) */
  w04 -= w09;
  /* #132: @9 = 3.14159 */
  w09 = 3.1415926535897931e+00;
  /* #133: @12 = (@9*@7) */
  w12  = (w09*w07);
  /* #134: @11 = cos(@12) */
  w11 = cos( w12 );
  /* #135: @9 = (@9*@10) */
  w09 *= w10;
  /* #136: @11 = (@11*@9) */
  w11 *= w09;
  /* #137: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #138: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #139: @12 = (@12*@6) */
  w12 *= w06;
  /* #140: @11 = (@11+@12) */
  w11 += w12;
  /* #141: @4 = (@4+@11) */
  w04 += w11;
  /* #142: @11 = -909.583 */
  w11 = -9.0958274160439521e+02;
  /* #143: @12 = @14[1] */
  for (rr=(&w12), cs=w14+1; cs!=w14+2; cs+=1) *rr++ = *cs;
  /* #144: @11 = (@11*@12) */
  w11 *= w12;
  /* #145: @12 = 0.482549 */
  w12 = 4.8254863159139222e-01;
  /* #146: @12 = (@12*@3) */
  w12 *= w03;
  /* #147: @11 = (@11-@12) */
  w11 -= w12;
  /* #148: @12 = 6.28319 */
  w12 = 6.2831853071795862e+00;
  /* #149: @7 = (@12*@7) */
  w07  = (w12*w07);
  /* #150: @9 = cos(@7) */
  w09 = cos( w07 );
  /* #151: @12 = (@12*@10) */
  w12 *= w10;
  /* #152: @9 = (@9*@12) */
  w09 *= w12;
  /* #153: @5 = (@5*@9) */
  w05 *= w09;
  /* #154: @7 = sin(@7) */
  w07 = sin( w07 );
  /* #155: @7 = (@7*@6) */
  w07 *= w06;
  /* #156: @5 = (@5+@7) */
  w05 += w07;
  /* #157: @11 = (@11+@5) */
  w11 += w05;
  /* #158: @14 = vertcat(@2, @3, @4, @11) */
  rr=w14;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w11;
  /* #159: @13 = (@13+@14) */
  for (i=0, rr=w13, cs=w14; i<4; ++i) (*rr++) += (*cs++);
  /* #160: @13 = (@1*@13) */
  for (i=0, rr=w13, cs=w13; i<4; ++i) (*rr++)  = (w01*(*cs++));
  /* #161: @0 = (@0+@13) */
  for (i=0, rr=w00, cs=w13; i<4; ++i) (*rr++) += (*cs++);
  /* #162: output[0][0] = @0 */
  casadi_copy(w00, 4, res[0]);
  return 0;
}

/* fwd1_step_acc10:(i0[4],i1[1x10],i2[1x10],out_o0[4x10,0nz],fwd_i0[4],fwd_i1[1x10],fwd_i2[1x10])->(fwd_o0[4x10]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w00=w+28, w01, w02, *w04=w+34, w06, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  casadi_real w25, *w26=w+68;
  const casadi_real **arg1=arg+7, *wr05;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 4, w00);
  /* #1: @1 = input[1][0] */
  w01 = arg[1] ? arg[1][0] : 0;
  /* #2: @2 = input[2][0] */
  w02 = arg[2] ? arg[2][0] : 0;
  /* #3: @3 = zeros(4x1,0nz) */
  /* #4: @4 = input[4][0] */
  casadi_copy(arg[4], 4, w04);
  /* #5: @5 = input[5][0] */
  wr05 = arg[5] ? arg[5] : casadi_zeros;
  /* #6: {@6, @7, @8, @9, @10, @11, @12, @13, @14, @15} = horzsplit(@5) */
  w06 = wr05[0];
  w07 = wr05[1];
  w08 = wr05[2];
  w09 = wr05[3];
  w10 = wr05[4];
  w11 = wr05[5];
  w12 = wr05[6];
  w13 = wr05[7];
  w14 = wr05[8];
  w15 = wr05[9];
  /* #7: @5 = input[6][0] */
  wr05 = arg[6] ? arg[6] : casadi_zeros;
  /* #8: {@16, @17, @18, @19, @20, @21, @22, @23, @24, @25} = horzsplit(@5) */
  w16 = wr05[0];
  w17 = wr05[1];
  w18 = wr05[2];
  w19 = wr05[3];
  w20 = wr05[4];
  w21 = wr05[5];
  w22 = wr05[6];
  w23 = wr05[7];
  w24 = wr05[8];
  w25 = wr05[9];
  /* #9: @26 = fwd1_step(@0, @1, @2, @3, @4, @6, @16) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=(&w06);
  arg1[6]=(&w16);
  res1[0]=w26;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][0] = @26 */
  casadi_copy(w26, 4, res[0]);
  /* #11: @4 = step(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w04;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: @1 = input[1][1] */
  w01 = arg[1] ? arg[1][1] : 0;
  /* #13: @2 = input[2][1] */
  w02 = arg[2] ? arg[2][1] : 0;
  /* #14: @3 = zeros(4x1,0nz) */
  /* #15: @0 = fwd1_step(@4, @1, @2, @3, @26, @7, @17) */
  arg1[0]=w04;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w26;
  arg1[5]=(&w07);
  arg1[6]=(&w17);
  res1[0]=w00;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #16: output[0][1] = @0 */
  if (res[0]) casadi_copy(w00, 4, res[0]+4);
  /* #17: @26 = step(@4, @1, @2) */
  arg1[0]=w04;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w26;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #18: @1 = input[1][2] */
  w01 = arg[1] ? arg[1][2] : 0;
  /* #19: @2 = input[2][2] */
  w02 = arg[2] ? arg[2][2] : 0;
  /* #20: @3 = zeros(4x1,0nz) */
  /* #21: @4 = fwd1_step(@26, @1, @2, @3, @0, @8, @18) */
  arg1[0]=w26;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w00;
  arg1[5]=(&w08);
  arg1[6]=(&w18);
  res1[0]=w04;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #22: output[0][2] = @4 */
  if (res[0]) casadi_copy(w04, 4, res[0]+8);
  /* #23: @0 = step(@26, @1, @2) */
  arg1[0]=w26;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w00;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #24: @1 = input[1][3] */
  w01 = arg[1] ? arg[1][3] : 0;
  /* #25: @2 = input[2][3] */
  w02 = arg[2] ? arg[2][3] : 0;
  /* #26: @3 = zeros(4x1,0nz) */
  /* #27: @26 = fwd1_step(@0, @1, @2, @3, @4, @9, @19) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=(&w09);
  arg1[6]=(&w19);
  res1[0]=w26;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #28: output[0][3] = @26 */
  if (res[0]) casadi_copy(w26, 4, res[0]+12);
  /* #29: @4 = step(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w04;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #30: @1 = input[1][4] */
  w01 = arg[1] ? arg[1][4] : 0;
  /* #31: @2 = input[2][4] */
  w02 = arg[2] ? arg[2][4] : 0;
  /* #32: @3 = zeros(4x1,0nz) */
  /* #33: @0 = fwd1_step(@4, @1, @2, @3, @26, @10, @20) */
  arg1[0]=w04;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w26;
  arg1[5]=(&w10);
  arg1[6]=(&w20);
  res1[0]=w00;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #34: output[0][4] = @0 */
  if (res[0]) casadi_copy(w00, 4, res[0]+16);
  /* #35: @26 = step(@4, @1, @2) */
  arg1[0]=w04;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w26;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #36: @1 = input[1][5] */
  w01 = arg[1] ? arg[1][5] : 0;
  /* #37: @2 = input[2][5] */
  w02 = arg[2] ? arg[2][5] : 0;
  /* #38: @3 = zeros(4x1,0nz) */
  /* #39: @4 = fwd1_step(@26, @1, @2, @3, @0, @11, @21) */
  arg1[0]=w26;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w00;
  arg1[5]=(&w11);
  arg1[6]=(&w21);
  res1[0]=w04;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #40: output[0][5] = @4 */
  if (res[0]) casadi_copy(w04, 4, res[0]+20);
  /* #41: @0 = step(@26, @1, @2) */
  arg1[0]=w26;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w00;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #42: @1 = input[1][6] */
  w01 = arg[1] ? arg[1][6] : 0;
  /* #43: @2 = input[2][6] */
  w02 = arg[2] ? arg[2][6] : 0;
  /* #44: @3 = zeros(4x1,0nz) */
  /* #45: @26 = fwd1_step(@0, @1, @2, @3, @4, @12, @22) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=(&w12);
  arg1[6]=(&w22);
  res1[0]=w26;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #46: output[0][6] = @26 */
  if (res[0]) casadi_copy(w26, 4, res[0]+24);
  /* #47: @4 = step(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w04;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #48: @1 = input[1][7] */
  w01 = arg[1] ? arg[1][7] : 0;
  /* #49: @2 = input[2][7] */
  w02 = arg[2] ? arg[2][7] : 0;
  /* #50: @3 = zeros(4x1,0nz) */
  /* #51: @0 = fwd1_step(@4, @1, @2, @3, @26, @13, @23) */
  arg1[0]=w04;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w26;
  arg1[5]=(&w13);
  arg1[6]=(&w23);
  res1[0]=w00;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #52: output[0][7] = @0 */
  if (res[0]) casadi_copy(w00, 4, res[0]+28);
  /* #53: @26 = step(@4, @1, @2) */
  arg1[0]=w04;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w26;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #54: @1 = input[1][8] */
  w01 = arg[1] ? arg[1][8] : 0;
  /* #55: @2 = input[2][8] */
  w02 = arg[2] ? arg[2][8] : 0;
  /* #56: @3 = zeros(4x1,0nz) */
  /* #57: @4 = fwd1_step(@26, @1, @2, @3, @0, @14, @24) */
  arg1[0]=w26;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w00;
  arg1[5]=(&w14);
  arg1[6]=(&w24);
  res1[0]=w04;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #58: output[0][8] = @4 */
  if (res[0]) casadi_copy(w04, 4, res[0]+32);
  /* #59: @0 = step(@26, @1, @2) */
  arg1[0]=w26;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  res1[0]=w00;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #60: @1 = input[1][9] */
  w01 = arg[1] ? arg[1][9] : 0;
  /* #61: @2 = input[2][9] */
  w02 = arg[2] ? arg[2][9] : 0;
  /* #62: @3 = zeros(4x1,0nz) */
  /* #63: @26 = fwd1_step(@0, @1, @2, @3, @4, @15, @25) */
  arg1[0]=w00;
  arg1[1]=(&w01);
  arg1[2]=(&w02);
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=(&w15);
  arg1[6]=(&w25);
  res1[0]=w26;
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #64: output[0][9] = @26 */
  if (res[0]) casadi_copy(w26, 4, res[0]+36);
  return 0;
}

/* fwd1_roll:(i0[4],i1[1x60],i2[1x60],out_o0[4x60,0nz],fwd_i0[4],fwd_i1[1x60],fwd_i2[1x60])->(fwd_o0[4x60]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w00=w+72, *w04=w+96, *w18=w+280, *w19=w+320;
  const casadi_real **arg1=arg+7, *wr01, *wr02, *wr05, *wr06, *wr07, *wr08, *wr09, *wr10, *wr11, *wr12, *wr13;
  const casadi_real *wr14, *wr15, *wr16, *wr17;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 4, w00);
  /* #1: @1 = input[1][0] */
  wr01 = arg[1] ? arg[1] : casadi_zeros;
  /* #2: @2 = input[2][0] */
  wr02 = arg[2] ? arg[2] : casadi_zeros;
  /* #3: @3 = zeros(4x10,0nz) */
  /* #4: @4 = input[4][0] */
  casadi_copy(arg[4], 4, w04);
  /* #5: @5 = input[5][0] */
  wr05 = arg[5] ? arg[5] : casadi_zeros;
  /* #6: {@6, @7, @8, @9, @10, @11} = horzsplit(@5) */
  wr06 = wr05;
  wr07 = wr05+10;
  wr08 = wr05+20;
  wr09 = wr05+30;
  wr10 = wr05+40;
  wr11 = wr05+50;
  /* #7: @5 = input[6][0] */
  wr05 = arg[6] ? arg[6] : casadi_zeros;
  /* #8: {@12, @13, @14, @15, @16, @17} = horzsplit(@5) */
  wr12 = wr05;
  wr13 = wr05+10;
  wr14 = wr05+20;
  wr15 = wr05+30;
  wr16 = wr05+40;
  wr17 = wr05+50;
  /* #9: @18 = fwd1_step_acc10(@0, @1, @2, @3, @4, @6, @12) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=wr06;
  arg1[6]=wr12;
  res1[0]=w18;
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][0] = @18 */
  casadi_copy(w18, 40, res[0]);
  /* #11: @19 = step_acc10(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: {NULL, @0} = horzsplit(@19) */
  casadi_copy(w19+36, 4, w00);
  /* #13: @1 = input[1][1] */
  wr01 = arg[1] ? arg[1]+10 : casadi_zeros;
  /* #14: @2 = input[2][1] */
  wr02 = arg[2] ? arg[2]+10 : casadi_zeros;
  /* #15: @3 = zeros(4x10,0nz) */
  /* #16: {NULL, @4} = horzsplit(@18) */
  casadi_copy(w18+36, 4, w04);
  /* #17: @18 = fwd1_step_acc10(@0, @1, @2, @3, @4, @7, @13) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=wr07;
  arg1[6]=wr13;
  res1[0]=w18;
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #18: output[0][1] = @18 */
  if (res[0]) casadi_copy(w18, 40, res[0]+40);
  /* #19: @19 = step_acc10(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: {NULL, @0} = horzsplit(@19) */
  casadi_copy(w19+36, 4, w00);
  /* #21: @1 = input[1][2] */
  wr01 = arg[1] ? arg[1]+20 : casadi_zeros;
  /* #22: @2 = input[2][2] */
  wr02 = arg[2] ? arg[2]+20 : casadi_zeros;
  /* #23: @3 = zeros(4x10,0nz) */
  /* #24: {NULL, @4} = horzsplit(@18) */
  casadi_copy(w18+36, 4, w04);
  /* #25: @18 = fwd1_step_acc10(@0, @1, @2, @3, @4, @8, @14) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=wr08;
  arg1[6]=wr14;
  res1[0]=w18;
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #26: output[0][2] = @18 */
  if (res[0]) casadi_copy(w18, 40, res[0]+80);
  /* #27: @19 = step_acc10(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: {NULL, @0} = horzsplit(@19) */
  casadi_copy(w19+36, 4, w00);
  /* #29: @1 = input[1][3] */
  wr01 = arg[1] ? arg[1]+30 : casadi_zeros;
  /* #30: @2 = input[2][3] */
  wr02 = arg[2] ? arg[2]+30 : casadi_zeros;
  /* #31: @3 = zeros(4x10,0nz) */
  /* #32: {NULL, @4} = horzsplit(@18) */
  casadi_copy(w18+36, 4, w04);
  /* #33: @18 = fwd1_step_acc10(@0, @1, @2, @3, @4, @9, @15) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=wr09;
  arg1[6]=wr15;
  res1[0]=w18;
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #34: output[0][3] = @18 */
  if (res[0]) casadi_copy(w18, 40, res[0]+120);
  /* #35: @19 = step_acc10(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #36: {NULL, @0} = horzsplit(@19) */
  casadi_copy(w19+36, 4, w00);
  /* #37: @1 = input[1][4] */
  wr01 = arg[1] ? arg[1]+40 : casadi_zeros;
  /* #38: @2 = input[2][4] */
  wr02 = arg[2] ? arg[2]+40 : casadi_zeros;
  /* #39: @3 = zeros(4x10,0nz) */
  /* #40: {NULL, @4} = horzsplit(@18) */
  casadi_copy(w18+36, 4, w04);
  /* #41: @18 = fwd1_step_acc10(@0, @1, @2, @3, @4, @10, @16) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=wr10;
  arg1[6]=wr16;
  res1[0]=w18;
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #42: output[0][4] = @18 */
  if (res[0]) casadi_copy(w18, 40, res[0]+160);
  /* #43: @19 = step_acc10(@0, @1, @2) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #44: {NULL, @0} = horzsplit(@19) */
  casadi_copy(w19+36, 4, w00);
  /* #45: @1 = input[1][5] */
  wr01 = arg[1] ? arg[1]+50 : casadi_zeros;
  /* #46: @2 = input[2][5] */
  wr02 = arg[2] ? arg[2]+50 : casadi_zeros;
  /* #47: @3 = zeros(4x10,0nz) */
  /* #48: {NULL, @4} = horzsplit(@18) */
  casadi_copy(w18+36, 4, w04);
  /* #49: @18 = fwd1_step_acc10(@0, @1, @2, @3, @4, @11, @17) */
  arg1[0]=w00;
  arg1[1]=wr01;
  arg1[2]=wr02;
  arg1[3]=0;
  arg1[4]=w04;
  arg1[5]=wr11;
  arg1[6]=wr17;
  res1[0]=w18;
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #50: output[0][5] = @18 */
  if (res[0]) casadi_copy(w18, 40, res[0]+200);
  return 0;
}

/* F_dp_p:(i0[60],i1)->(o0) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, *w01=w+360, w03, *w04=w+425, *w06=w+485, *w07=w+489, *w08=w+549, *w09=w+609, *w10=w+849;
  const casadi_real **arg1=arg+2, *cs, *wr02;
  /* #0: @0 = zeros(4x1,0nz) */
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w01, 4);
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @2 = @2' */
  /* #4: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #5: @4 = repmat(@3, 60) */
  for (i=0;i<60;++i) {
    casadi_copy((&w03), 1, w04+ i*1);
  }
  /* #6: @5 = zeros(4x60,0nz) */
  /* #7: @6 = zeros(4x1) */
  casadi_clear(w06, 4);
  /* #8: @7 = zeros(1x60) */
  casadi_clear(w07, 60);
  /* #9: @3 = 1 */
  w03 = 1.;
  /* #10: @8 = repmat(@3, 60) */
  for (i=0;i<60;++i) {
    casadi_copy((&w03), 1, w08+ i*1);
  }
  /* #11: @9 = fwd1_roll(@1, @2, @4, @5, @6, @7, @8) */
  arg1[0]=w01;
  arg1[1]=wr02;
  arg1[2]=w04;
  arg1[3]=0;
  arg1[4]=w06;
  arg1[5]=w07;
  arg1[6]=w08;
  res1[0]=w09;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #12: @10 = horzcat(@0, @9) */
  rr=w10;
  for (i=0, cs=w09; i<240; ++i) *rr++ = *cs++;
  /* #13: @9 = @10' */
  casadi_trans(w10,casadi_s4, w09, casadi_s5, iw);
  /* #14: @3 = @9[239] */
  for (rr=(&w03), cs=w09+239; cs!=w09+240; cs+=1) *rr++ = *cs;
  /* #15: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_dp_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_dp_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_dp_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_dp_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_dp_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_dp_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_dp_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_dp_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_dp_p_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_dp_p_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_dp_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_dp_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_dp_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_dp_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_dp_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_dp_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 27;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 1089;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_dp_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 27*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 1089*sizeof(casadi_real);
  return 0;
}

/* F_roll_p:(i0[60],i1)->(o0[61x4]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+1, *rr, *w0=w+98, *w1=w+102, w3, *w4=w+167, *w5=w+227, *w6=w+467, *w7=w+711;
  const casadi_real **arg1=arg+2, *cs, *wr2;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[0][0] */
  wr2 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @2 = @2' */
  /* #4: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #5: @4 = repmat(@3, 60) */
  for (i=0;i<60;++i) {
    casadi_copy((&w3), 1, w4+ i*1);
  }
  /* #6: @5 = roll(@1, @2, @4) */
  arg1[0]=w1;
  arg1[1]=wr2;
  arg1[2]=w4;
  res1[0]=w5;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @6 = horzcat(@0, @5) */
  rr=w6;
  for (i=0, cs=w0; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<240; ++i) *rr++ = *cs++;
  /* #8: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<61; ++i) for (j=0; j<4; ++j) rr[i+j*61] = *cs++;
  /* #9: output[0][0] = @7 */
  casadi_copy(w7, 244, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int F_roll_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_roll_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_roll_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_roll_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_roll_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_roll_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_roll_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_roll_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_roll_p_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_roll_p_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_roll_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_roll_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_roll_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_roll_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_roll_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_roll_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 955;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_roll_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 955*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
